// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Response.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "Response.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

Response::Response()
{
    // m_q_exp com.eprosima.idl.parser.typecode.ArrayTypeCode@4fb64261
    memset(&m_q_exp, 0, (10) * 4);

}

Response::~Response()
{
}

Response::Response(
        const Response& x)
{
    m_q_exp = x.m_q_exp;
}

Response::Response(
        Response&& x)
{
    m_q_exp = std::move(x.m_q_exp);
}

Response& Response::operator =(
        const Response& x)
{

    m_q_exp = x.m_q_exp;

    return *this;
}

Response& Response::operator =(
        Response&& x)
{

    m_q_exp = std::move(x.m_q_exp);

    return *this;
}

bool Response::operator ==(
        const Response& x) const
{

    return (m_q_exp == x.m_q_exp);
}

bool Response::operator !=(
        const Response& x) const
{
    return !(*this == x);
}

size_t Response::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += ((10) * 4) + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    return current_alignment - initial_alignment;
}

size_t Response::getCdrSerializedSize(
        const Response& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    if ((10) > 0)
    {
        current_alignment += ((10) * 4) + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);
    }

    return current_alignment - initial_alignment;
}

void Response::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_q_exp;


}

void Response::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_q_exp;

}

/*!
 * @brief This function copies the value in member q_exp
 * @param _q_exp New value to be copied in member q_exp
 */
void Response::q_exp(
        const std::array<float, 10>& _q_exp)
{
    m_q_exp = _q_exp;
}

/*!
 * @brief This function moves the value in member q_exp
 * @param _q_exp New value to be moved in member q_exp
 */
void Response::q_exp(
        std::array<float, 10>&& _q_exp)
{
    m_q_exp = std::move(_q_exp);
}

/*!
 * @brief This function returns a constant reference to member q_exp
 * @return Constant reference to member q_exp
 */
const std::array<float, 10>& Response::q_exp() const
{
    return m_q_exp;
}

/*!
 * @brief This function returns a reference to member q_exp
 * @return Reference to member q_exp
 */
std::array<float, 10>& Response::q_exp()
{
    return m_q_exp;
}

size_t Response::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;



    return current_align;
}

bool Response::isKeyDefined()
{
    return false;
}

void Response::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
     
}
