// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: ESP32Box

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void text_Animation(lv_obj_t * TargetObject, int delay);


// SCREEN: ui_Start
void ui_Start_screen_init(void);
void ui_event_Start(lv_event_t * e);
lv_obj_t * ui_Start;
lv_obj_t * ui_Image1;
lv_obj_t * ui_Spinner1;
void ui_event_Label21(lv_event_t * e);
lv_obj_t * ui_Label21;
// CUSTOM VARIABLES


// SCREEN: ui_ScreenWifi
void ui_ScreenWifi_screen_init(void);
lv_obj_t * ui_ScreenWifi;
void ui_event_KeyboardWifi(lv_event_t * e);
lv_obj_t * ui_KeyboardWifi;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Label8;
void ui_event_TextAreaIP(lv_event_t * e);
lv_obj_t * ui_TextAreaIP;
lv_obj_t * ui_Label9;
void ui_event_TextAreaPwd(lv_event_t * e);
lv_obj_t * ui_TextAreaPwd;
void ui_event_ButtonLogin(lv_event_t * e);
lv_obj_t * ui_ButtonLogin;
lv_obj_t * ui_Label10;
lv_obj_t * ui_DropdownRobotSel;
lv_obj_t * ui_DropdownRobot;
// CUSTOM VARIABLES


// SCREEN: ui_ScreenRC
void ui_ScreenRC_screen_init(void);
lv_obj_t * ui_ScreenRC;
void ui_event_ButtonParam(lv_event_t * e);
lv_obj_t * ui_ButtonParam;
lv_obj_t * ui_Label;
void ui_event_SwitchAuto(lv_event_t * e);
lv_obj_t * ui_SwitchAuto;
lv_obj_t * ui_LabelIP;
lv_obj_t * ui_LabelLocal;
lv_obj_t * ui_ButtonLight;
void ui_event_ButtonPower(lv_event_t * e);
lv_obj_t * ui_ButtonPower;
lv_obj_t * ui_LabelPower;
lv_obj_t * ui_LabelMode;
lv_obj_t * ui_LabelGPTshow;
lv_obj_t * ui_LabelGPT;
lv_obj_t * ui_LabelMShow;
lv_obj_t * ui_LabelAuto;
void ui_event_ButtonJointArm1(lv_event_t * e);
lv_obj_t * ui_ButtonJointArm1;
lv_obj_t * ui_LabelGPT1;
void ui_event_ButtonJointArm2(lv_event_t * e);
lv_obj_t * ui_ButtonJointArm2;
lv_obj_t * ui_LabelMisson;
void ui_event_ButtonJointArm3(lv_event_t * e);
lv_obj_t * ui_ButtonJointArm3;
lv_obj_t * ui_LabelGPT3;
lv_obj_t * ui_ImageButtonRC;
void ui_event_PanelRight(lv_event_t * e);
lv_obj_t * ui_PanelRight;
void ui_event_PanelUp(lv_event_t * e);
lv_obj_t * ui_PanelUp;
void ui_event_PanelDown(lv_event_t * e);
lv_obj_t * ui_PanelDown;
void ui_event_PanelMid(lv_event_t * e);
lv_obj_t * ui_PanelMid;
void ui_event_PanelLeft(lv_event_t * e);
lv_obj_t * ui_PanelLeft;
lv_obj_t * ui_ImageButtonRC2;
lv_obj_t * ui_ArrowDown;
lv_obj_t * ui_ArrowUp;
lv_obj_t * ui_ArrowRight;
lv_obj_t * ui_ArrowLeft;
lv_obj_t * ui_ImageButton0;
void ui_event_Panel1(lv_event_t * e);
lv_obj_t * ui_Panel1;
lv_obj_t * ui_ImageButton1;
void ui_event_Panel2(lv_event_t * e);
lv_obj_t * ui_Panel2;
lv_obj_t * ui_ImageButton2;
void ui_event_Panel3(lv_event_t * e);
lv_obj_t * ui_Panel3;
lv_obj_t * ui_ImageButton3;
void ui_event_Panel4(lv_event_t * e);
lv_obj_t * ui_Panel4;
// CUSTOM VARIABLES


// SCREEN: ui_ScreenSystem
void ui_ScreenSystem_screen_init(void);
lv_obj_t * ui_ScreenSystem;
void ui_event_Button3(lv_event_t * e);
lv_obj_t * ui_Button3;
lv_obj_t * ui_Dropdown1;
lv_obj_t * ui_CheckboxHead;
void ui_event_SliderSpeed(lv_event_t * e);
lv_obj_t * ui_SliderSpeed;
lv_obj_t * ui_Label2;
lv_obj_t * ui_LabelSpeed;
void ui_event_Button1(lv_event_t * e);
lv_obj_t * ui_Button1;
lv_obj_t * ui_Label3;
void ui_event_SliderHeight(lv_event_t * e);
lv_obj_t * ui_SliderHeight;
lv_obj_t * ui_LabelHeight;
lv_obj_t * ui_CheckboxSW;
void ui_event_ButtonJointLeg(lv_event_t * e);
lv_obj_t * ui_ButtonJointLeg;
lv_obj_t * ui_Labeljoint;
void ui_event_ButtonJointArm(lv_event_t * e);
lv_obj_t * ui_ButtonJointArm;
lv_obj_t * ui_LabelArm;
void ui_event_ButtonSensor(lv_event_t * e);
lv_obj_t * ui_ButtonSensor;
lv_obj_t * ui_LabelSensor;
lv_obj_t * ui_CheckboxSW1;
void ui_event_SliderSpeed1(lv_event_t * e);
lv_obj_t * ui_SliderSpeed1;
lv_obj_t * ui_LabelRad;
void ui_event_Button4(lv_event_t * e);
lv_obj_t * ui_Button4;
lv_obj_t * ui_Label28;
lv_obj_t * ui_CheckboxSW2;
lv_obj_t * ui_CheckboxSW3;
void ui_event_SliderStep(lv_event_t * e);
lv_obj_t * ui_SliderStep;
lv_obj_t * ui_LabelStep;
// CUSTOM VARIABLES


// SCREEN: ui_ScreenLeg
void ui_ScreenLeg_screen_init(void);
lv_obj_t * ui_ScreenLeg;
lv_obj_t * ui_TabView3;
lv_obj_t * ui_TabPage5;
lv_obj_t * ui_TabPage6;
lv_obj_t * ui_TabPage7;
lv_obj_t * ui_TabPage8;
lv_obj_t * ui_TabPage1;
void ui_event_ButtonParam1(lv_event_t * e);
lv_obj_t * ui_ButtonParam1;
lv_obj_t * ui_ButtonLight1;
lv_obj_t * ui_Label11;
lv_obj_t * ui_Label12;
lv_obj_t * ui_LabelL01;
lv_obj_t * ui_LabelL02;
lv_obj_t * ui_LabelL03;
lv_obj_t * ui_Label13;
lv_obj_t * ui_LabelL11;
lv_obj_t * ui_LabelL12;
lv_obj_t * ui_LabelL13;
lv_obj_t * ui_Label15;
lv_obj_t * ui_LabelL21;
lv_obj_t * ui_LabelL22;
lv_obj_t * ui_LabelL23;
lv_obj_t * ui_Label16;
lv_obj_t * ui_LabelL25;
lv_obj_t * ui_LabelL26;
lv_obj_t * ui_LabelL27;
lv_obj_t * ui_LabelL31;
lv_obj_t * ui_LabelL32;
lv_obj_t * ui_LabelL33;
lv_obj_t * ui_LabelL35;
lv_obj_t * ui_LabelL36;
lv_obj_t * ui_LabelL37;
void ui_event_ButtonCal(lv_event_t * e);
lv_obj_t * ui_ButtonCal;
lv_obj_t * ui_LabelLocal2;
lv_obj_t * ui_DropdownCalLeg1;
lv_obj_t * ui_DropdownCalLeg2;
lv_obj_t * ui_LabelL04;
lv_obj_t * ui_LabelL14;
lv_obj_t * ui_LabelL24;
lv_obj_t * ui_LabelL28;
lv_obj_t * ui_LabelL34;
lv_obj_t * ui_LabelL38;
lv_obj_t * ui_LabelLocal3;
// CUSTOM VARIABLES


// SCREEN: ui_ScreenArm
void ui_ScreenArm_screen_init(void);
lv_obj_t * ui_ScreenArm;
lv_obj_t * ui_TabView1;
lv_obj_t * ui_TabPage2;
lv_obj_t * ui_TabPage3;
lv_obj_t * ui_TabPage4;
lv_obj_t * ui_TabPage9;
lv_obj_t * ui_TabPage10;
void ui_event_ButtonParam2(lv_event_t * e);
lv_obj_t * ui_ButtonParam2;
lv_obj_t * ui_ButtonLight2;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Label4;
lv_obj_t * ui_LabelA01;
lv_obj_t * ui_LabelA02;
lv_obj_t * ui_LabelA03;
lv_obj_t * ui_Label6;
lv_obj_t * ui_LabelA11;
lv_obj_t * ui_LabelA12;
lv_obj_t * ui_LabelA13;
lv_obj_t * ui_Label14;
lv_obj_t * ui_LabelA21;
lv_obj_t * ui_LabelA22;
lv_obj_t * ui_LabelA23;
lv_obj_t * ui_Label17;
lv_obj_t * ui_LabelA25;
lv_obj_t * ui_LabelA26;
lv_obj_t * ui_LabelA27;
lv_obj_t * ui_LabelA31;
lv_obj_t * ui_LabelA32;
lv_obj_t * ui_LabelA33;
lv_obj_t * ui_LabelA35;
lv_obj_t * ui_LabelA36;
lv_obj_t * ui_LabelA37;
void ui_event_ButtonCal1(lv_event_t * e);
lv_obj_t * ui_ButtonCal1;
lv_obj_t * ui_LabelLocal4;
lv_obj_t * ui_DropdownCalArm1;
lv_obj_t * ui_DropdownCalArm2;
lv_obj_t * ui_LabelA04;
lv_obj_t * ui_LabelA14;
lv_obj_t * ui_LabelA24;
lv_obj_t * ui_LabelA28;
lv_obj_t * ui_LabelA34;
lv_obj_t * ui_LabelA38;
lv_obj_t * ui_LabelLocal6;
// CUSTOM VARIABLES


// SCREEN: ui_Screenlogin
void ui_Screenlogin_screen_init(void);
lv_obj_t * ui_Screenlogin;
lv_obj_t * ui_SpinnerLogin;
lv_obj_t * ui_Label18;
// CUSTOM VARIABLES


// SCREEN: ui_ScreenGPT
void ui_ScreenGPT_screen_init(void);
lv_obj_t * ui_ScreenGPT;
void ui_event_ButtonParam3(lv_event_t * e);
lv_obj_t * ui_ButtonParam3;
lv_obj_t * ui_LabelLocal5;
lv_obj_t * ui_LabelIP3;
lv_obj_t * ui_ButtonLight3;
lv_obj_t * ui_Label5;
lv_obj_t * ui_TabGPT;
lv_obj_t * ui_ChartData;
void ui_event_ButtonParam5(lv_event_t * e);
lv_obj_t * ui_ButtonParam5;
lv_obj_t * ui_Label29;
lv_obj_t * ui_CheckboxGPT1;
lv_obj_t * ui_Dropdown3;
// CUSTOM VARIABLES


// SCREEN: ui_ScreenloginGood
void ui_ScreenloginGood_screen_init(void);
void ui_event_ScreenloginGood(lv_event_t * e);
lv_obj_t * ui_ScreenloginGood;
lv_obj_t * ui_Label20;
lv_obj_t * ui_Image2;
// CUSTOM VARIABLES


// SCREEN: ui_ScreenSensor
void ui_ScreenSensor_screen_init(void);
lv_obj_t * ui_ScreenSensor;
lv_obj_t * ui_TabView2;
lv_obj_t * ui_TabPage11;
lv_obj_t * ui_TabPage12;
lv_obj_t * ui_TabPage13;
lv_obj_t * ui_TabPage14;
lv_obj_t * ui_TabPage15;
void ui_event_ButtonParam4(lv_event_t * e);
lv_obj_t * ui_ButtonParam4;
lv_obj_t * ui_ButtonLight4;
lv_obj_t * ui_Label22;
lv_obj_t * ui_Label23;
lv_obj_t * ui_LabelS01;
lv_obj_t * ui_LabelS02;
lv_obj_t * ui_LabelS03;
lv_obj_t * ui_Label24;
lv_obj_t * ui_LabelS11;
lv_obj_t * ui_LabelS12;
lv_obj_t * ui_LabelS13;
lv_obj_t * ui_Label25;
lv_obj_t * ui_LabelS21;
lv_obj_t * ui_LabelS22;
lv_obj_t * ui_LabelS23;
lv_obj_t * ui_Label26;
lv_obj_t * ui_LabelS31;
lv_obj_t * ui_LabelS32;
lv_obj_t * ui_LabelS33;
lv_obj_t * ui_LabelS41;
lv_obj_t * ui_LabelS42;
lv_obj_t * ui_LabelS43;
void ui_event_ButtonCal2(lv_event_t * e);
lv_obj_t * ui_ButtonCal2;
lv_obj_t * ui_LabelLocal1;
lv_obj_t * ui_DropdownCalSensor;
lv_obj_t * ui_LabelS04;
lv_obj_t * ui_LabelS14;
lv_obj_t * ui_LabelS24;
lv_obj_t * ui_LabelS34;
lv_obj_t * ui_LabelS44;
lv_obj_t * ui_LabelLocal7;
lv_obj_t * ui_Label27;
// CUSTOM VARIABLES


// SCREEN: ui_ScreenACT
void ui_ScreenACT_screen_init(void);
lv_obj_t * ui_ScreenACT;
void ui_event_ButtonParam6(lv_event_t * e);
lv_obj_t * ui_ButtonParam6;
lv_obj_t * ui_Label30;
lv_obj_t * ui_LabelLocal8;
lv_obj_t * ui_LabelIP1;
lv_obj_t * ui_ButtonLight5;
void ui_event_BarACTrate(lv_event_t * e);
lv_obj_t * ui_BarACTrate;
lv_obj_t * ui_LabelACTrate;
void ui_event_ButtonParam7(lv_event_t * e);
lv_obj_t * ui_ButtonParam7;
lv_obj_t * ui_Label31;
void ui_event_ButtonParam9(lv_event_t * e);
lv_obj_t * ui_ButtonParam9;
lv_obj_t * ui_Label33;
void ui_event_ButtonParam10(lv_event_t * e);
lv_obj_t * ui_ButtonParam10;
lv_obj_t * ui_Label34;
lv_obj_t * ui_DropdownReplay;
lv_obj_t * ui_DropdownModel;
lv_obj_t * ui_DropdownRecord;
void ui_event_ButtonParam11(lv_event_t * e);
lv_obj_t * ui_ButtonParam11;
lv_obj_t * ui_Label35;
lv_obj_t * ui_TabViewACT;
// CUSTOM VARIABLES


// SCREEN: ui_ScreenMission
void ui_ScreenMission_screen_init(void);
lv_obj_t * ui_ScreenMission;
void ui_event_ButtonParam8(lv_event_t * e);
lv_obj_t * ui_ButtonParam8;
lv_obj_t * ui_Label32;
lv_obj_t * ui_LabelLocal9;
lv_obj_t * ui_LabelIP2;
lv_obj_t * ui_ButtonLight6;
lv_obj_t * ui_Panel5;
lv_obj_t * ui_Image3;
lv_obj_t * ui_SwitchVideo;
lv_obj_t * ui_Label36;
void ui_event_ButtonParam12(lv_event_t * e);
lv_obj_t * ui_ButtonParam12;
lv_obj_t * ui_Label37;
void ui_event_ButtonParam13(lv_event_t * e);
lv_obj_t * ui_ButtonParam13;
lv_obj_t * ui_Label38;
void ui_event_ButtonParam14(lv_event_t * e);
lv_obj_t * ui_ButtonParam14;
lv_obj_t * ui_Label39;
lv_obj_t * ui_RollerWaypoints;
// CUSTOM VARIABLES


// SCREEN: ui_ScreenloginFail
void ui_ScreenloginFail_screen_init(void);
lv_obj_t * ui_ScreenloginFail;
lv_obj_t * ui_Label40;
void ui_event_Button2(lv_event_t * e);
lv_obj_t * ui_Button2;
lv_obj_t * ui_Label19;
lv_obj_t * ui_Image5;
void ui_event_Button5(lv_event_t * e);
lv_obj_t * ui_Button5;
void ui_event_Label41(lv_event_t * e);
lv_obj_t * ui_Label41;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_img_dsc_t * ui_imgset_icn_time_[2] = {&ui_img_icn_time_1_png, &ui_img_icn_time_2_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void text_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 600);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_0, 0, 255);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_in_out);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_opacity);
    lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_Start(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenWifi, LV_SCR_LOAD_ANIM_FADE_ON, 250, 0, &ui_ScreenWifi_screen_init);
    }
}

void ui_event_Label21(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        text_Animation(ui_Label21, 9);
    }
}

void ui_event_KeyboardWifi(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        keyinput(e);
    }
}

void ui_event_TextAreaIP(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        selectIP(e);
    }
}

void ui_event_TextAreaPwd(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        seletpwd(e);
    }
}

void ui_event_ButtonLogin(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ConnetWifi(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screenlogin, LV_SCR_LOAD_ANIM_FADE_ON, 250, 0, &ui_Screenlogin_screen_init);
    }
}

void ui_event_ButtonParam(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenSystem, LV_SCR_LOAD_ANIM_FADE_ON, 250, 0, &ui_ScreenSystem_screen_init);
    }
}

void ui_event_SwitchAuto(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        switchauto(e);
    }
}

void ui_event_ButtonPower(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        event_power(e);
    }
    if(event_code == LV_EVENT_RELEASED) {
        event_powerr(e);
    }
}

void ui_event_ButtonJointArm1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenGPT, LV_SCR_LOAD_ANIM_FADE_ON, 250, 0, &ui_ScreenGPT_screen_init);
    }
}

void ui_event_ButtonJointArm2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenMission, LV_SCR_LOAD_ANIM_FADE_ON, 250, 0, &ui_ScreenMission_screen_init);
    }
}

void ui_event_ButtonJointArm3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenACT, LV_SCR_LOAD_ANIM_FADE_ON, 250, 0, &ui_ScreenACT_screen_init);
    }
}

void ui_event_PanelRight(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_state_modify(ui_ArrowRight, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        ButtonRight(e);
    }
    if(event_code == LV_EVENT_RELEASED) {
        _ui_state_modify(ui_ArrowRight, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        ButtonRightr(e);
    }
}

void ui_event_PanelUp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_state_modify(ui_ArrowUp, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        ButtonUp(e);
    }
    if(event_code == LV_EVENT_RELEASED) {
        _ui_state_modify(ui_ArrowUp, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        ButtonUpr(e);
    }
}

void ui_event_PanelDown(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_state_modify(ui_ArrowDown, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        ButtonDown(e);
    }
    if(event_code == LV_EVENT_RELEASED) {
        _ui_state_modify(ui_ArrowDown, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        ButtonDownr(e);
    }
}

void ui_event_PanelMid(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_state_modify(ui_ImageButtonRC2, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        ButtonMid(e);
    }
    if(event_code == LV_EVENT_RELEASED) {
        _ui_state_modify(ui_ImageButtonRC2, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        ButtonMidr(e);
    }
}

void ui_event_PanelLeft(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_state_modify(ui_ArrowLeft, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        ButtonLeft(e);
    }
    if(event_code == LV_EVENT_RELEASED) {
        _ui_state_modify(ui_ArrowLeft, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        ButtonLeftr(e);
    }
}

void ui_event_Panel1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_state_modify(ui_ImageButton0, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        ButtonRC0(e);
    }
    if(event_code == LV_EVENT_RELEASED) {
        _ui_state_modify(ui_ImageButton0, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}

void ui_event_Panel2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_state_modify(ui_ImageButton1, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        ButtonRC1(e);
    }
    if(event_code == LV_EVENT_RELEASED) {
        _ui_state_modify(ui_ImageButton1, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}

void ui_event_Panel3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_state_modify(ui_ImageButton2, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        ButtonRC2(e);
    }
    if(event_code == LV_EVENT_RELEASED) {
        _ui_state_modify(ui_ImageButton2, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}

void ui_event_Panel4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_state_modify(ui_ImageButton3, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        ButtonRC3(e);
    }
    if(event_code == LV_EVENT_RELEASED) {
        _ui_state_modify(ui_ImageButton3, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}

void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenRC, LV_SCR_LOAD_ANIM_FADE_ON, 250, 0, &ui_ScreenRC_screen_init);
    }
}

void ui_event_SliderSpeed(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_LabelSpeed, target, "0.", "m/s");
    }
}

void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        System_set(e);
    }
}

void ui_event_SliderHeight(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_LabelHeight, target, "H=", "%");
    }
}

void ui_event_ButtonJointLeg(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenLeg, LV_SCR_LOAD_ANIM_FADE_ON, 250, 0, &ui_ScreenLeg_screen_init);
    }
}

void ui_event_ButtonJointArm(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenArm, LV_SCR_LOAD_ANIM_FADE_ON, 250, 0, &ui_ScreenArm_screen_init);
    }
}

void ui_event_ButtonSensor(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenSensor, LV_SCR_LOAD_ANIM_FADE_ON, 250, 0, &ui_ScreenSensor_screen_init);
    }
}

void ui_event_SliderSpeed1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_LabelRad, target, "0.", "m/s");
    }
}

void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        System_set(e);
    }
}

void ui_event_SliderStep(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_LabelStep, target, "Step=", "%");
    }
}

void ui_event_ButtonParam1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenSystem, LV_SCR_LOAD_ANIM_FADE_ON, 250, 0, &ui_ScreenSystem_screen_init);
    }
}

void ui_event_ButtonCal(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        calleg(e);
    }
}

void ui_event_ButtonParam2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenSystem, LV_SCR_LOAD_ANIM_FADE_ON, 250, 0, &ui_ScreenSystem_screen_init);
    }
}

void ui_event_ButtonCal1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        calarm(e);
    }
}

void ui_event_ButtonParam3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenRC, LV_SCR_LOAD_ANIM_FADE_ON, 250, 0, &ui_ScreenRC_screen_init);
    }
}

void ui_event_ButtonParam5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        GPTListen(e);
    }
    if(event_code == LV_EVENT_RELEASED) {
        GPTListenr(e);
    }
}

void ui_event_ScreenloginGood(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenRC, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenRC_screen_init);
    }
}

void ui_event_ButtonParam4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenSystem, LV_SCR_LOAD_ANIM_FADE_ON, 250, 0, &ui_ScreenSystem_screen_init);
    }
}

void ui_event_ButtonCal2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        calimu(e);
    }
}

void ui_event_ButtonParam6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenRC, LV_SCR_LOAD_ANIM_FADE_ON, 250, 0, &ui_ScreenRC_screen_init);
    }
}

void ui_event_BarACTrate(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_label_set_property(ui_LabelACTrate, _UI_LABEL_PROPERTY_TEXT, "%");
    }
}

void ui_event_ButtonParam7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        act_record(e);
    }
}

void ui_event_ButtonParam9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        act_replay(e);
    }
}

void ui_event_ButtonParam10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        act_perception(e);
    }
}

void ui_event_ButtonParam11(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        act_stop(e);
    }
}

void ui_event_ButtonParam8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenRC, LV_SCR_LOAD_ANIM_FADE_ON, 250, 0, &ui_ScreenRC_screen_init);
    }
}

void ui_event_ButtonParam12(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Mission_home(e);
    }
}

void ui_event_ButtonParam13(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Mission_stop(e);
    }
}

void ui_event_ButtonParam14(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Mission_way(e);
    }
}

void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenRC, LV_SCR_LOAD_ANIM_FADE_ON, 250, 0, &ui_ScreenRC_screen_init);
    }
}

void ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenWifi, LV_SCR_LOAD_ANIM_FADE_ON, 250, 0, &ui_ScreenWifi_screen_init);
    }
}

void ui_event_Label41(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenWifi, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenWifi_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Start_screen_init();
    ui_ScreenWifi_screen_init();
    ui_ScreenRC_screen_init();
    ui_ScreenSystem_screen_init();
    ui_ScreenLeg_screen_init();
    ui_ScreenArm_screen_init();
    ui_Screenlogin_screen_init();
    ui_ScreenGPT_screen_init();
    ui_ScreenloginGood_screen_init();
    ui_ScreenSensor_screen_init();
    ui_ScreenACT_screen_init();
    ui_ScreenMission_screen_init();
    ui_ScreenloginFail_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Start);
}
