// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: ESP32Box

#ifndef _ESP32BOX_UI_H
#define _ESP32BOX_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void text_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_Start
void ui_Start_screen_init(void);
void ui_event_Start(lv_event_t * e);
extern lv_obj_t * ui_Start;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Spinner1;
void ui_event_Label21(lv_event_t * e);
extern lv_obj_t * ui_Label21;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenWifi
void ui_ScreenWifi_screen_init(void);
extern lv_obj_t * ui_ScreenWifi;
void ui_event_KeyboardWifi(lv_event_t * e);
extern lv_obj_t * ui_KeyboardWifi;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
void ui_event_TextAreaIP(lv_event_t * e);
extern lv_obj_t * ui_TextAreaIP;
extern lv_obj_t * ui_Label9;
void ui_event_TextAreaPwd(lv_event_t * e);
extern lv_obj_t * ui_TextAreaPwd;
void ui_event_ButtonLogin(lv_event_t * e);
extern lv_obj_t * ui_ButtonLogin;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_DropdownRobotSel;
extern lv_obj_t * ui_DropdownRobot;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenRC
void ui_ScreenRC_screen_init(void);
extern lv_obj_t * ui_ScreenRC;
void ui_event_ButtonParam(lv_event_t * e);
extern lv_obj_t * ui_ButtonParam;
extern lv_obj_t * ui_Label;
void ui_event_SwitchAuto(lv_event_t * e);
extern lv_obj_t * ui_SwitchAuto;
extern lv_obj_t * ui_LabelIP;
extern lv_obj_t * ui_LabelLocal;
extern lv_obj_t * ui_ButtonLight;
void ui_event_ButtonPower(lv_event_t * e);
extern lv_obj_t * ui_ButtonPower;
extern lv_obj_t * ui_LabelPower;
extern lv_obj_t * ui_LabelMode;
extern lv_obj_t * ui_LabelGPTshow;
extern lv_obj_t * ui_LabelGPT;
extern lv_obj_t * ui_LabelMShow;
extern lv_obj_t * ui_LabelAuto;
void ui_event_ButtonJointArm1(lv_event_t * e);
extern lv_obj_t * ui_ButtonJointArm1;
extern lv_obj_t * ui_LabelGPT1;
void ui_event_ButtonJointArm2(lv_event_t * e);
extern lv_obj_t * ui_ButtonJointArm2;
extern lv_obj_t * ui_LabelMisson;
void ui_event_ButtonJointArm3(lv_event_t * e);
extern lv_obj_t * ui_ButtonJointArm3;
extern lv_obj_t * ui_LabelGPT3;
extern lv_obj_t * ui_ImageButtonRC;
void ui_event_PanelRight(lv_event_t * e);
extern lv_obj_t * ui_PanelRight;
void ui_event_PanelUp(lv_event_t * e);
extern lv_obj_t * ui_PanelUp;
void ui_event_PanelDown(lv_event_t * e);
extern lv_obj_t * ui_PanelDown;
void ui_event_PanelMid(lv_event_t * e);
extern lv_obj_t * ui_PanelMid;
void ui_event_PanelLeft(lv_event_t * e);
extern lv_obj_t * ui_PanelLeft;
extern lv_obj_t * ui_ImageButtonRC2;
extern lv_obj_t * ui_ArrowDown;
extern lv_obj_t * ui_ArrowUp;
extern lv_obj_t * ui_ArrowRight;
extern lv_obj_t * ui_ArrowLeft;
extern lv_obj_t * ui_ImageButton0;
void ui_event_Panel1(lv_event_t * e);
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_ImageButton1;
void ui_event_Panel2(lv_event_t * e);
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_ImageButton2;
void ui_event_Panel3(lv_event_t * e);
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_ImageButton3;
void ui_event_Panel4(lv_event_t * e);
extern lv_obj_t * ui_Panel4;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenSystem
void ui_ScreenSystem_screen_init(void);
extern lv_obj_t * ui_ScreenSystem;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Dropdown1;
extern lv_obj_t * ui_CheckboxHead;
void ui_event_SliderSpeed(lv_event_t * e);
extern lv_obj_t * ui_SliderSpeed;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_LabelSpeed;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label3;
void ui_event_SliderHeight(lv_event_t * e);
extern lv_obj_t * ui_SliderHeight;
extern lv_obj_t * ui_LabelHeight;
extern lv_obj_t * ui_CheckboxSW;
void ui_event_ButtonJointLeg(lv_event_t * e);
extern lv_obj_t * ui_ButtonJointLeg;
extern lv_obj_t * ui_Labeljoint;
void ui_event_ButtonJointArm(lv_event_t * e);
extern lv_obj_t * ui_ButtonJointArm;
extern lv_obj_t * ui_LabelArm;
void ui_event_ButtonSensor(lv_event_t * e);
extern lv_obj_t * ui_ButtonSensor;
extern lv_obj_t * ui_LabelSensor;
extern lv_obj_t * ui_CheckboxSW1;
void ui_event_SliderSpeed1(lv_event_t * e);
extern lv_obj_t * ui_SliderSpeed1;
extern lv_obj_t * ui_LabelRad;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_CheckboxSW2;
extern lv_obj_t * ui_CheckboxSW3;
void ui_event_SliderStep(lv_event_t * e);
extern lv_obj_t * ui_SliderStep;
extern lv_obj_t * ui_LabelStep;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenLeg
void ui_ScreenLeg_screen_init(void);
extern lv_obj_t * ui_ScreenLeg;
extern lv_obj_t * ui_TabView3;
extern lv_obj_t * ui_TabPage5;
extern lv_obj_t * ui_TabPage6;
extern lv_obj_t * ui_TabPage7;
extern lv_obj_t * ui_TabPage8;
extern lv_obj_t * ui_TabPage1;
void ui_event_ButtonParam1(lv_event_t * e);
extern lv_obj_t * ui_ButtonParam1;
extern lv_obj_t * ui_ButtonLight1;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_LabelL01;
extern lv_obj_t * ui_LabelL02;
extern lv_obj_t * ui_LabelL03;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_LabelL11;
extern lv_obj_t * ui_LabelL12;
extern lv_obj_t * ui_LabelL13;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_LabelL21;
extern lv_obj_t * ui_LabelL22;
extern lv_obj_t * ui_LabelL23;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_LabelL25;
extern lv_obj_t * ui_LabelL26;
extern lv_obj_t * ui_LabelL27;
extern lv_obj_t * ui_LabelL31;
extern lv_obj_t * ui_LabelL32;
extern lv_obj_t * ui_LabelL33;
extern lv_obj_t * ui_LabelL35;
extern lv_obj_t * ui_LabelL36;
extern lv_obj_t * ui_LabelL37;
void ui_event_ButtonCal(lv_event_t * e);
extern lv_obj_t * ui_ButtonCal;
extern lv_obj_t * ui_LabelLocal2;
extern lv_obj_t * ui_DropdownCalLeg1;
extern lv_obj_t * ui_DropdownCalLeg2;
extern lv_obj_t * ui_LabelL04;
extern lv_obj_t * ui_LabelL14;
extern lv_obj_t * ui_LabelL24;
extern lv_obj_t * ui_LabelL28;
extern lv_obj_t * ui_LabelL34;
extern lv_obj_t * ui_LabelL38;
extern lv_obj_t * ui_LabelLocal3;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenArm
void ui_ScreenArm_screen_init(void);
extern lv_obj_t * ui_ScreenArm;
extern lv_obj_t * ui_TabView1;
extern lv_obj_t * ui_TabPage2;
extern lv_obj_t * ui_TabPage3;
extern lv_obj_t * ui_TabPage4;
extern lv_obj_t * ui_TabPage9;
extern lv_obj_t * ui_TabPage10;
void ui_event_ButtonParam2(lv_event_t * e);
extern lv_obj_t * ui_ButtonParam2;
extern lv_obj_t * ui_ButtonLight2;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_LabelA01;
extern lv_obj_t * ui_LabelA02;
extern lv_obj_t * ui_LabelA03;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_LabelA11;
extern lv_obj_t * ui_LabelA12;
extern lv_obj_t * ui_LabelA13;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_LabelA21;
extern lv_obj_t * ui_LabelA22;
extern lv_obj_t * ui_LabelA23;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_LabelA25;
extern lv_obj_t * ui_LabelA26;
extern lv_obj_t * ui_LabelA27;
extern lv_obj_t * ui_LabelA31;
extern lv_obj_t * ui_LabelA32;
extern lv_obj_t * ui_LabelA33;
extern lv_obj_t * ui_LabelA35;
extern lv_obj_t * ui_LabelA36;
extern lv_obj_t * ui_LabelA37;
void ui_event_ButtonCal1(lv_event_t * e);
extern lv_obj_t * ui_ButtonCal1;
extern lv_obj_t * ui_LabelLocal4;
extern lv_obj_t * ui_DropdownCalArm1;
extern lv_obj_t * ui_DropdownCalArm2;
extern lv_obj_t * ui_LabelA04;
extern lv_obj_t * ui_LabelA14;
extern lv_obj_t * ui_LabelA24;
extern lv_obj_t * ui_LabelA28;
extern lv_obj_t * ui_LabelA34;
extern lv_obj_t * ui_LabelA38;
extern lv_obj_t * ui_LabelLocal6;
// CUSTOM VARIABLES

// SCREEN: ui_Screenlogin
void ui_Screenlogin_screen_init(void);
extern lv_obj_t * ui_Screenlogin;
extern lv_obj_t * ui_SpinnerLogin;
extern lv_obj_t * ui_Label18;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenGPT
void ui_ScreenGPT_screen_init(void);
extern lv_obj_t * ui_ScreenGPT;
void ui_event_ButtonParam3(lv_event_t * e);
extern lv_obj_t * ui_ButtonParam3;
extern lv_obj_t * ui_LabelLocal5;
extern lv_obj_t * ui_LabelIP3;
extern lv_obj_t * ui_ButtonLight3;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_TabGPT;
extern lv_obj_t * ui_ChartData;
void ui_event_ButtonParam5(lv_event_t * e);
extern lv_obj_t * ui_ButtonParam5;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_CheckboxGPT1;
extern lv_obj_t * ui_Dropdown3;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenloginGood
void ui_ScreenloginGood_screen_init(void);
void ui_event_ScreenloginGood(lv_event_t * e);
extern lv_obj_t * ui_ScreenloginGood;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Image2;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenSensor
void ui_ScreenSensor_screen_init(void);
extern lv_obj_t * ui_ScreenSensor;
extern lv_obj_t * ui_TabView2;
extern lv_obj_t * ui_TabPage11;
extern lv_obj_t * ui_TabPage12;
extern lv_obj_t * ui_TabPage13;
extern lv_obj_t * ui_TabPage14;
extern lv_obj_t * ui_TabPage15;
void ui_event_ButtonParam4(lv_event_t * e);
extern lv_obj_t * ui_ButtonParam4;
extern lv_obj_t * ui_ButtonLight4;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_LabelS01;
extern lv_obj_t * ui_LabelS02;
extern lv_obj_t * ui_LabelS03;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_LabelS11;
extern lv_obj_t * ui_LabelS12;
extern lv_obj_t * ui_LabelS13;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_LabelS21;
extern lv_obj_t * ui_LabelS22;
extern lv_obj_t * ui_LabelS23;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_LabelS31;
extern lv_obj_t * ui_LabelS32;
extern lv_obj_t * ui_LabelS33;
extern lv_obj_t * ui_LabelS41;
extern lv_obj_t * ui_LabelS42;
extern lv_obj_t * ui_LabelS43;
void ui_event_ButtonCal2(lv_event_t * e);
extern lv_obj_t * ui_ButtonCal2;
extern lv_obj_t * ui_LabelLocal1;
extern lv_obj_t * ui_DropdownCalSensor;
extern lv_obj_t * ui_LabelS04;
extern lv_obj_t * ui_LabelS14;
extern lv_obj_t * ui_LabelS24;
extern lv_obj_t * ui_LabelS34;
extern lv_obj_t * ui_LabelS44;
extern lv_obj_t * ui_LabelLocal7;
extern lv_obj_t * ui_Label27;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenACT
void ui_ScreenACT_screen_init(void);
extern lv_obj_t * ui_ScreenACT;
void ui_event_ButtonParam6(lv_event_t * e);
extern lv_obj_t * ui_ButtonParam6;
extern lv_obj_t * ui_Label30;
extern lv_obj_t * ui_LabelLocal8;
extern lv_obj_t * ui_LabelIP1;
extern lv_obj_t * ui_ButtonLight5;
void ui_event_BarACTrate(lv_event_t * e);
extern lv_obj_t * ui_BarACTrate;
extern lv_obj_t * ui_LabelACTrate;
void ui_event_ButtonParam7(lv_event_t * e);
extern lv_obj_t * ui_ButtonParam7;
extern lv_obj_t * ui_Label31;
void ui_event_ButtonParam9(lv_event_t * e);
extern lv_obj_t * ui_ButtonParam9;
extern lv_obj_t * ui_Label33;
void ui_event_ButtonParam10(lv_event_t * e);
extern lv_obj_t * ui_ButtonParam10;
extern lv_obj_t * ui_Label34;
extern lv_obj_t * ui_DropdownReplay;
extern lv_obj_t * ui_DropdownModel;
extern lv_obj_t * ui_DropdownRecord;
void ui_event_ButtonParam11(lv_event_t * e);
extern lv_obj_t * ui_ButtonParam11;
extern lv_obj_t * ui_Label35;
extern lv_obj_t * ui_TabViewACT;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenMission
void ui_ScreenMission_screen_init(void);
extern lv_obj_t * ui_ScreenMission;
void ui_event_ButtonParam8(lv_event_t * e);
extern lv_obj_t * ui_ButtonParam8;
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_LabelLocal9;
extern lv_obj_t * ui_LabelIP2;
extern lv_obj_t * ui_ButtonLight6;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_SwitchVideo;
extern lv_obj_t * ui_Label36;
void ui_event_ButtonParam12(lv_event_t * e);
extern lv_obj_t * ui_ButtonParam12;
extern lv_obj_t * ui_Label37;
void ui_event_ButtonParam13(lv_event_t * e);
extern lv_obj_t * ui_ButtonParam13;
extern lv_obj_t * ui_Label38;
void ui_event_ButtonParam14(lv_event_t * e);
extern lv_obj_t * ui_ButtonParam14;
extern lv_obj_t * ui_Label39;
extern lv_obj_t * ui_RollerWaypoints;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenloginFail
void ui_ScreenloginFail_screen_init(void);
extern lv_obj_t * ui_ScreenloginFail;
extern lv_obj_t * ui_Label40;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Image5;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
void ui_event_Label41(lv_event_t * e);
extern lv_obj_t * ui_Label41;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_1822533526);    // assets/无标题(1).png
LV_IMG_DECLARE(ui_img_btn_pad_bottom_png);    // assets/btn_pad_bottom.png
LV_IMG_DECLARE(ui_img_btn_pad_top_png);    // assets/btn_pad_top.png
LV_IMG_DECLARE(ui_img_arrow_down_png);    // assets/arrow_down.png
LV_IMG_DECLARE(ui_img_arrow_up_png);    // assets/arrow_up.png
LV_IMG_DECLARE(ui_img_arrow_right_png);    // assets/arrow_right.png
LV_IMG_DECLARE(ui_img_arrow_left_png);    // assets/arrow_left.png
LV_IMG_DECLARE(ui_img_btn_main_off_png);    // assets/btn_main_off.png
LV_IMG_DECLARE(ui_img_705703283);    // assets/ok(1).png
LV_IMG_DECLARE(ui_img_1700300519);    // assets/捕获(1).png
LV_IMG_DECLARE(ui_img_icn_time_1_png);    // assets/icn_time_1.png
LV_IMG_DECLARE(ui_img_icn_time_2_png);    // assets/icn_time_2.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
