// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: ESP32Box

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void keyinput(lv_event_t * e);
void selectIP(lv_event_t * e);
void seletpwd(lv_event_t * e);
void ConnetWifi(lv_event_t * e);
void switchauto(lv_event_t * e);
void event_power(lv_event_t * e);
void event_powerr(lv_event_t * e);
void ButtonRight(lv_event_t * e);
void ButtonRightr(lv_event_t * e);
void ButtonUp(lv_event_t * e);
void ButtonUpr(lv_event_t * e);
void ButtonDown(lv_event_t * e);
void ButtonDownr(lv_event_t * e);
void ButtonMid(lv_event_t * e);
void ButtonMidr(lv_event_t * e);
void ButtonLeft(lv_event_t * e);
void ButtonLeftr(lv_event_t * e);
void ButtonRC0(lv_event_t * e);
void ButtonRC1(lv_event_t * e);
void ButtonRC2(lv_event_t * e);
void ButtonRC3(lv_event_t * e);
void System_set(lv_event_t * e);
void calleg(lv_event_t * e);
void calarm(lv_event_t * e);
void GPTListen(lv_event_t * e);
void GPTListenr(lv_event_t * e);
void calimu(lv_event_t * e);
void act_record(lv_event_t * e);
void act_replay(lv_event_t * e);
void act_perception(lv_event_t * e);
void act_stop(lv_event_t * e);
void Mission_home(lv_event_t * e);
void Mission_stop(lv_event_t * e);
void Mission_way(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
