// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Request.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "Request.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

Request::Request()
{
    // m_omega com.eprosima.idl.parser.typecode.ArrayTypeCode@544a2ea6
    memset(&m_omega, 0, (3) * 4);
    // m_eu_ang com.eprosima.idl.parser.typecode.ArrayTypeCode@2e3fc542
    memset(&m_eu_ang, 0, (3) * 4);
    // m_command com.eprosima.idl.parser.typecode.ArrayTypeCode@150c158
    memset(&m_command, 0, (3) * 4);
    // m_q com.eprosima.idl.parser.typecode.ArrayTypeCode@4524411f
    memset(&m_q, 0, (10) * 4);
    // m_dq com.eprosima.idl.parser.typecode.ArrayTypeCode@401e7803
    memset(&m_dq, 0, (10) * 4);
    // m_gait_type com.eprosima.idl.parser.typecode.ArrayTypeCode@10dba097
    memset(&m_gait_type, 0, (1) * 4);

}

Request::~Request()
{





}

Request::Request(
        const Request& x)
{
    m_omega = x.m_omega;
    m_eu_ang = x.m_eu_ang;
    m_command = x.m_command;
    m_q = x.m_q;
    m_dq = x.m_dq;
    m_gait_type = x.m_gait_type;
}

Request::Request(
        Request&& x)
{
    m_omega = std::move(x.m_omega);
    m_eu_ang = std::move(x.m_eu_ang);
    m_command = std::move(x.m_command);
    m_q = std::move(x.m_q);
    m_dq = std::move(x.m_dq);
    m_gait_type = std::move(x.m_gait_type);
}

Request& Request::operator =(
        const Request& x)
{

    m_omega = x.m_omega;
    m_eu_ang = x.m_eu_ang;
    m_command = x.m_command;
    m_q = x.m_q;
    m_dq = x.m_dq;
    m_gait_type = x.m_gait_type;

    return *this;
}

Request& Request::operator =(
        Request&& x)
{

    m_omega = std::move(x.m_omega);
    m_eu_ang = std::move(x.m_eu_ang);
    m_command = std::move(x.m_command);
    m_q = std::move(x.m_q);
    m_dq = std::move(x.m_dq);
    m_gait_type = std::move(x.m_gait_type);

    return *this;
}

bool Request::operator ==(
        const Request& x) const
{

    return (m_omega == x.m_omega && m_eu_ang == x.m_eu_ang && m_command == x.m_command && m_q == x.m_q && m_dq == x.m_dq && m_gait_type == x.m_gait_type);
}

bool Request::operator !=(
        const Request& x) const
{
    return !(*this == x);
}

size_t Request::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += ((3) * 4) + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += ((3) * 4) + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += ((3) * 4) + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += ((10) * 4) + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += ((10) * 4) + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += ((1) * 4) + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}

size_t Request::getCdrSerializedSize(
        const Request& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    if ((3) > 0)
    {
        current_alignment += ((3) * 4) + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);
    }

    if ((3) > 0)
    {
        current_alignment += ((3) * 4) + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);
    }

    if ((3) > 0)
    {
        current_alignment += ((3) * 4) + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);
    }

    if ((10) > 0)
    {
        current_alignment += ((10) * 4) + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);
    }

    if ((10) > 0)
    {
        current_alignment += ((10) * 4) + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);
    }

    if ((1) > 0)
    {
        current_alignment += ((1) * 4) + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);
    }


    return current_alignment - initial_alignment;
}

void Request::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_omega;

    scdr << m_eu_ang;

    scdr << m_command;

    scdr << m_q;

    scdr << m_dq;

    scdr << m_gait_type;


}

void Request::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_omega;

    dcdr >> m_eu_ang;

    dcdr >> m_command;

    dcdr >> m_q;

    dcdr >> m_dq;

    dcdr >> m_gait_type;

}

/*!
 * @brief This function copies the value in member omega
 * @param _omega New value to be copied in member omega
 */
void Request::omega(
        const std::array<float, 3>& _omega)
{
    m_omega = _omega;
}

/*!
 * @brief This function moves the value in member omega
 * @param _omega New value to be moved in member omega
 */
void Request::omega(
        std::array<float, 3>&& _omega)
{
    m_omega = std::move(_omega);
}

/*!
 * @brief This function returns a constant reference to member omega
 * @return Constant reference to member omega
 */
const std::array<float, 3>& Request::omega() const
{
    return m_omega;
}

/*!
 * @brief This function returns a reference to member omega
 * @return Reference to member omega
 */
std::array<float, 3>& Request::omega()
{
    return m_omega;
}
/*!
 * @brief This function copies the value in member eu_ang
 * @param _eu_ang New value to be copied in member eu_ang
 */
void Request::eu_ang(
        const std::array<float, 3>& _eu_ang)
{
    m_eu_ang = _eu_ang;
}

/*!
 * @brief This function moves the value in member eu_ang
 * @param _eu_ang New value to be moved in member eu_ang
 */
void Request::eu_ang(
        std::array<float, 3>&& _eu_ang)
{
    m_eu_ang = std::move(_eu_ang);
}

/*!
 * @brief This function returns a constant reference to member eu_ang
 * @return Constant reference to member eu_ang
 */
const std::array<float, 3>& Request::eu_ang() const
{
    return m_eu_ang;
}

/*!
 * @brief This function returns a reference to member eu_ang
 * @return Reference to member eu_ang
 */
std::array<float, 3>& Request::eu_ang()
{
    return m_eu_ang;
}
/*!
 * @brief This function copies the value in member command
 * @param _command New value to be copied in member command
 */
void Request::command(
        const std::array<float, 3>& _command)
{
    m_command = _command;
}

/*!
 * @brief This function moves the value in member command
 * @param _command New value to be moved in member command
 */
void Request::command(
        std::array<float, 3>&& _command)
{
    m_command = std::move(_command);
}

/*!
 * @brief This function returns a constant reference to member command
 * @return Constant reference to member command
 */
const std::array<float, 3>& Request::command() const
{
    return m_command;
}

/*!
 * @brief This function returns a reference to member command
 * @return Reference to member command
 */
std::array<float, 3>& Request::command()
{
    return m_command;
}
/*!
 * @brief This function copies the value in member q
 * @param _q New value to be copied in member q
 */
void Request::q(
        const std::array<float, 10>& _q)
{
    m_q = _q;
}

/*!
 * @brief This function moves the value in member q
 * @param _q New value to be moved in member q
 */
void Request::q(
        std::array<float, 10>&& _q)
{
    m_q = std::move(_q);
}

/*!
 * @brief This function returns a constant reference to member q
 * @return Constant reference to member q
 */
const std::array<float, 10>& Request::q() const
{
    return m_q;
}

/*!
 * @brief This function returns a reference to member q
 * @return Reference to member q
 */
std::array<float, 10>& Request::q()
{
    return m_q;
}
/*!
 * @brief This function copies the value in member dq
 * @param _dq New value to be copied in member dq
 */
void Request::dq(
        const std::array<float, 10>& _dq)
{
    m_dq = _dq;
}

/*!
 * @brief This function moves the value in member dq
 * @param _dq New value to be moved in member dq
 */
void Request::dq(
        std::array<float, 10>&& _dq)
{
    m_dq = std::move(_dq);
}

/*!
 * @brief This function returns a constant reference to member dq
 * @return Constant reference to member dq
 */
const std::array<float, 10>& Request::dq() const
{
    return m_dq;
}

/*!
 * @brief This function returns a reference to member dq
 * @return Reference to member dq
 */
std::array<float, 10>& Request::dq()
{
    return m_dq;
}
/*!
 * @brief This function copies the value in member gait_type
 * @param _gait_type New value to be copied in member gait_type
 */
void Request::gait_type(
        const std::array<int32_t, 1>& _gait_type)
{
    m_gait_type = _gait_type;
}

/*!
 * @brief This function moves the value in member gait_type
 * @param _gait_type New value to be moved in member gait_type
 */
void Request::gait_type(
        std::array<int32_t, 1>&& _gait_type)
{
    m_gait_type = std::move(_gait_type);
}

/*!
 * @brief This function returns a constant reference to member gait_type
 * @return Constant reference to member gait_type
 */
const std::array<int32_t, 1>& Request::gait_type() const
{
    return m_gait_type;
}

/*!
 * @brief This function returns a reference to member gait_type
 * @return Reference to member gait_type
 */
std::array<int32_t, 1>& Request::gait_type()
{
    return m_gait_type;
}

size_t Request::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;



    return current_align;
}

bool Request::isKeyDefined()
{
    return false;
}

void Request::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
          
}
