// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Request.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _FAST_DDS_GENERATED_REQUEST_H_
#define _FAST_DDS_GENERATED_REQUEST_H_


#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(Request_SOURCE)
#define Request_DllAPI __declspec( dllexport )
#else
#define Request_DllAPI __declspec( dllimport )
#endif // Request_SOURCE
#else
#define Request_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define Request_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima


/*!
 * @brief This class represents the structure Request defined by the user in the IDL file.
 * @ingroup REQUEST
 */
class Request
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport Request();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~Request();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object Request that will be copied.
     */
    eProsima_user_DllExport Request(
            const Request& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object Request that will be copied.
     */
    eProsima_user_DllExport Request(
            Request&& x);

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object Request that will be copied.
     */
    eProsima_user_DllExport Request& operator =(
            const Request& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object Request that will be copied.
     */
    eProsima_user_DllExport Request& operator =(
            Request&& x);

    /*!
     * @brief Comparison operator.
     * @param x Request object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const Request& x) const;

    /*!
     * @brief Comparison operator.
     * @param x Request object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const Request& x) const;

    /*!
     * @brief This function copies the value in member omega
     * @param _omega New value to be copied in member omega
     */
    eProsima_user_DllExport void omega(
            const std::array<float, 3>& _omega);

    /*!
     * @brief This function moves the value in member omega
     * @param _omega New value to be moved in member omega
     */
    eProsima_user_DllExport void omega(
            std::array<float, 3>&& _omega);

    /*!
     * @brief This function returns a constant reference to member omega
     * @return Constant reference to member omega
     */
    eProsima_user_DllExport const std::array<float, 3>& omega() const;

    /*!
     * @brief This function returns a reference to member omega
     * @return Reference to member omega
     */
    eProsima_user_DllExport std::array<float, 3>& omega();
    /*!
     * @brief This function copies the value in member eu_ang
     * @param _eu_ang New value to be copied in member eu_ang
     */
    eProsima_user_DllExport void eu_ang(
            const std::array<float, 3>& _eu_ang);

    /*!
     * @brief This function moves the value in member eu_ang
     * @param _eu_ang New value to be moved in member eu_ang
     */
    eProsima_user_DllExport void eu_ang(
            std::array<float, 3>&& _eu_ang);

    /*!
     * @brief This function returns a constant reference to member eu_ang
     * @return Constant reference to member eu_ang
     */
    eProsima_user_DllExport const std::array<float, 3>& eu_ang() const;

    /*!
     * @brief This function returns a reference to member eu_ang
     * @return Reference to member eu_ang
     */
    eProsima_user_DllExport std::array<float, 3>& eu_ang();
    /*!
     * @brief This function copies the value in member command
     * @param _command New value to be copied in member command
     */
    eProsima_user_DllExport void command(
            const std::array<float, 3>& _command);

    /*!
     * @brief This function moves the value in member command
     * @param _command New value to be moved in member command
     */
    eProsima_user_DllExport void command(
            std::array<float, 3>&& _command);

    /*!
     * @brief This function returns a constant reference to member command
     * @return Constant reference to member command
     */
    eProsima_user_DllExport const std::array<float, 3>& command() const;

    /*!
     * @brief This function returns a reference to member command
     * @return Reference to member command
     */
    eProsima_user_DllExport std::array<float, 3>& command();
    /*!
     * @brief This function copies the value in member q
     * @param _q New value to be copied in member q
     */
    eProsima_user_DllExport void q(
            const std::array<float, 10>& _q);

    /*!
     * @brief This function moves the value in member q
     * @param _q New value to be moved in member q
     */
    eProsima_user_DllExport void q(
            std::array<float, 10>&& _q);

    /*!
     * @brief This function returns a constant reference to member q
     * @return Constant reference to member q
     */
    eProsima_user_DllExport const std::array<float, 10>& q() const;

    /*!
     * @brief This function returns a reference to member q
     * @return Reference to member q
     */
    eProsima_user_DllExport std::array<float, 10>& q();
    /*!
     * @brief This function copies the value in member dq
     * @param _dq New value to be copied in member dq
     */
    eProsima_user_DllExport void dq(
            const std::array<float, 10>& _dq);

    /*!
     * @brief This function moves the value in member dq
     * @param _dq New value to be moved in member dq
     */
    eProsima_user_DllExport void dq(
            std::array<float, 10>&& _dq);

    /*!
     * @brief This function returns a constant reference to member dq
     * @return Constant reference to member dq
     */
    eProsima_user_DllExport const std::array<float, 10>& dq() const;

    /*!
     * @brief This function returns a reference to member dq
     * @return Reference to member dq
     */
    eProsima_user_DllExport std::array<float, 10>& dq();
    /*!
     * @brief This function copies the value in member gait_type
     * @param _gait_type New value to be copied in member gait_type
     */
    eProsima_user_DllExport void gait_type(
            const std::array<int32_t, 1>& _gait_type);

    /*!
     * @brief This function moves the value in member gait_type
     * @param _gait_type New value to be moved in member gait_type
     */
    eProsima_user_DllExport void gait_type(
            std::array<int32_t, 1>&& _gait_type);

    /*!
     * @brief This function returns a constant reference to member gait_type
     * @return Constant reference to member gait_type
     */
    eProsima_user_DllExport const std::array<int32_t, 1>& gait_type() const;

    /*!
     * @brief This function returns a reference to member gait_type
     * @return Reference to member gait_type
     */
    eProsima_user_DllExport std::array<int32_t, 1>& gait_type();

    /*!
     * @brief This function returns the maximum serialized size of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
            size_t current_alignment = 0);

    /*!
     * @brief This function returns the serialized size of a data depending on the buffer alignment.
     * @param data Data which is calculated its serialized size.
     * @param current_alignment Buffer alignment.
     * @return Serialized size.
     */
    eProsima_user_DllExport static size_t getCdrSerializedSize(
            const Request& data,
            size_t current_alignment = 0);


    /*!
     * @brief This function serializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serialize(
            eprosima::fastcdr::Cdr& cdr) const;

    /*!
     * @brief This function deserializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void deserialize(
            eprosima::fastcdr::Cdr& cdr);



    /*!
     * @brief This function returns the maximum serialized size of the Key of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
            size_t current_alignment = 0);

    /*!
     * @brief This function tells you if the Key has been defined for this type
     */
    eProsima_user_DllExport static bool isKeyDefined();

    /*!
     * @brief This function serializes the key members of an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serializeKey(
            eprosima::fastcdr::Cdr& cdr) const;

private:

    std::array<float, 3> m_omega;
    std::array<float, 3> m_eu_ang;
    std::array<float, 3> m_command;
    std::array<float, 10> m_q;
    std::array<float, 10> m_dq;
    std::array<int32_t, 1> m_gait_type;
};

#endif // _FAST_DDS_GENERATED_REQUEST_H_