// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: ESP32Box

#include "../ui.h"
#include <stdio.h>
// 定义要显示的字符串和当前显示的索引
const char *full_text = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!";
char display_text[64];  // 用于存放增量显示的文本
int current_index = 0;  // 当前显示的字符索引
lv_obj_t *label;
lv_obj_t *tab1;

void increment_text(void) {
	 int max_text_length = 36;
    if (current_index < strlen(full_text)&& current_index<max_text_length) {
        display_text[current_index] = full_text[current_index];
        display_text[current_index + 1] = '\0';  // 确保字符串结尾为 null
		 
        lv_label_set_text(label, display_text);  // 更新标签显示的文本
		//printf("current_index=%d\n", current_index);
		//printf("display_text: %s\n", display_text);  // 打印当前的增量文本
        current_index++;  // 更新当前显示字符的索引
    }else{
    	display_text[0] = '\0';
		current_index=0;
	}
}

void ui_ScreenGPT_screen_init(void)
{
    ui_ScreenGPT = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenGPT, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenGPT, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenGPT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonParam3 = lv_btn_create(ui_ScreenGPT);
    lv_obj_set_width(ui_ButtonParam3, 70);
    lv_obj_set_height(ui_ButtonParam3, 28);
    lv_obj_set_x(ui_ButtonParam3, 117);
    lv_obj_set_y(ui_ButtonParam3, -103);
    lv_obj_set_align(ui_ButtonParam3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonParam3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonParam3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonParam3, lv_color_hex(0xF3E4E4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonParam3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelLocal5 = lv_label_create(ui_ScreenGPT);
    lv_obj_set_width(ui_LabelLocal5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelLocal5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelLocal5, -102);
    lv_obj_set_y(ui_LabelLocal5, -104);
    lv_obj_set_align(ui_LabelLocal5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelLocal5, "GPT:");

    ui_LabelIP3 = lv_label_create(ui_ScreenGPT);
    lv_obj_set_width(ui_LabelIP3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelIP3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelIP3, -6);
    lv_obj_set_y(ui_LabelIP3, -104);
    lv_obj_set_align(ui_LabelIP3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelIP3, "Network Disconnect");

    ui_ButtonLight3 = lv_btn_create(ui_ScreenGPT);
    lv_obj_set_width(ui_ButtonLight3, 23);
    lv_obj_set_height(ui_ButtonLight3, 18);
    lv_obj_set_x(ui_ButtonLight3, -139);
    lv_obj_set_y(ui_ButtonLight3, -105);
    lv_obj_set_align(ui_ButtonLight3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonLight3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonLight3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonLight3, 55, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_ButtonLight3, lv_color_hex(0xCCCCEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_ButtonLight3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ButtonLight3, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_ScreenGPT);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 117);
    lv_obj_set_y(ui_Label5, -102);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Back");
    lv_obj_clear_flag(ui_Label5, LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags

    ui_TabGPT = lv_tabview_create(ui_ScreenGPT, LV_DIR_TOP, 20);
    lv_obj_set_width(ui_TabGPT, 181);
    lv_obj_set_height(ui_TabGPT, 82);
    lv_obj_set_x(ui_TabGPT, -62);
    lv_obj_set_y(ui_TabGPT, -44);
    lv_obj_set_align(ui_TabGPT, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TabGPT, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TabGPT, lv_color_hex(0xF1CACA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabGPT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TabGPT, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TabGPT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TabGPT, 1, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_ChartData = lv_chart_create(ui_ScreenGPT);
    lv_obj_set_width(ui_ChartData, 183);
    lv_obj_set_height(ui_ChartData, 91);
    lv_obj_set_x(ui_ChartData, -53);
    lv_obj_set_y(ui_ChartData, 61);
    lv_obj_set_align(ui_ChartData, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_ChartData, LV_CHART_TYPE_LINE);
    lv_chart_set_range(ui_ChartData, LV_CHART_AXIS_PRIMARY_Y, -100, 100);
    lv_chart_set_range(ui_ChartData, LV_CHART_AXIS_SECONDARY_Y, -100, 100);
    lv_chart_set_axis_tick(ui_ChartData, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_ChartData, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, false, 50);
    lv_chart_set_axis_tick(ui_ChartData, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, false, 25);
    lv_chart_series_t * ui_ChartData_series_1 = lv_chart_add_series(ui_ChartData, lv_color_hex(0x808080),
                                                                    LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_ChartData_series_1_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 0 };
    lv_chart_set_ext_y_array(ui_ChartData, ui_ChartData_series_1, ui_ChartData_series_1_array);
    lv_chart_series_t * ui_ChartData_series_2 = lv_chart_add_series(ui_ChartData, lv_color_hex(0xE73838),
                                                                    LV_CHART_AXIS_SECONDARY_Y);
    static lv_coord_t ui_ChartData_series_2_array[] = { 0, 0, 50, 140, 30, 50, 60, 20, 10, 0, 2 };
    lv_chart_set_ext_y_array(ui_ChartData, ui_ChartData_series_2, ui_ChartData_series_2_array);
    lv_chart_series_t * ui_ChartData_series_3 = lv_chart_add_series(ui_ChartData, lv_color_hex(0xBFD81A),
                                                                    LV_CHART_AXIS_SECONDARY_Y);
    static lv_coord_t ui_ChartData_series_3_array[] = { 52, 110, 20, 40, 80, -80, 40, 20, 10, 0 };
    lv_chart_set_ext_y_array(ui_ChartData, ui_ChartData_series_3, ui_ChartData_series_3_array);



    ui_ButtonParam5 = lv_btn_create(ui_ScreenGPT);
    lv_obj_set_width(ui_ButtonParam5, 75);
    lv_obj_set_height(ui_ButtonParam5, 102);
    lv_obj_set_x(ui_ButtonParam5, 107);
    lv_obj_set_y(ui_ButtonParam5, 57);
    lv_obj_set_align(ui_ButtonParam5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonParam5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonParam5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonParam5, lv_color_hex(0xF3E4E4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonParam5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label29 = lv_label_create(ui_ButtonParam5);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label29, -1);
    lv_obj_set_y(ui_Label29, 0);
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, "Listen");
    lv_obj_set_style_text_color(ui_Label29, lv_color_hex(0x0B0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label29, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CheckboxGPT1 = lv_checkbox_create(ui_ScreenGPT);
    lv_checkbox_set_text(ui_CheckboxGPT1, "Enable API");
    lv_obj_set_width(ui_CheckboxGPT1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CheckboxGPT1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CheckboxGPT1, 93);
    lv_obj_set_y(ui_CheckboxGPT1, -64);
    lv_obj_set_align(ui_CheckboxGPT1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CheckboxGPT1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Dropdown3 = lv_dropdown_create(ui_ScreenGPT);
    lv_dropdown_set_options(ui_Dropdown3, "GPT4o\nBaidu\nZhipu\nClude");
    lv_obj_set_width(ui_Dropdown3, 109);
    lv_obj_set_height(ui_Dropdown3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown3, 94);
    lv_obj_set_y(ui_Dropdown3, -26);
    lv_obj_set_align(ui_Dropdown3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    // 创建 Tab 页 "Tab 1"
    tab1 = lv_tabview_add_tab(ui_TabGPT, "Chat GTP");
    label = lv_label_create(tab1);  // 传入 tab1，作为父对象
    lv_obj_set_width(label, 160); // 设置标签宽度为 像素宽度
    lv_label_set_long_mode(label, LV_LABEL_LONG_WRAP);  // 启用自动换行
    lv_label_set_text(label, full_text);  // 设置显示的文本
    display_text[0] = '\0';

    lv_obj_add_event_cb(ui_ButtonParam3, ui_event_ButtonParam3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonParam5, ui_event_ButtonParam5, LV_EVENT_ALL, NULL);

}
