// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: ESP32Box

#include "../ui.h"

void ui_ScreenSystem_screen_init(void)
{
    ui_ScreenSystem = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenSystem, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenSystem, lv_color_hex(0xF1F1F1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenSystem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3 = lv_btn_create(ui_ScreenSystem);
    lv_obj_set_width(ui_Button3, 56);
    lv_obj_set_height(ui_Button3, 28);
    lv_obj_set_x(ui_Button3, 120);
    lv_obj_set_y(ui_Button3, 96);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0xF2E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dropdown1 = lv_dropdown_create(ui_ScreenSystem);
    lv_dropdown_set_options(ui_Dropdown1,
                            "Idel Mode\nTrack Mode\nBall Mode\nSLAM Mode\nCharge Mode\nGPT Mode\nDance Mode1\nDance Mode2\nDance Mode3\nDance Mode4");
    lv_obj_set_width(ui_Dropdown1, 136);
    lv_obj_set_height(ui_Dropdown1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown1, -80);
    lv_obj_set_y(ui_Dropdown1, -88);
    lv_obj_set_align(ui_Dropdown1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_CheckboxHead = lv_checkbox_create(ui_ScreenSystem);
    lv_checkbox_set_text(ui_CheckboxHead, "Head Auto Mode");
    lv_obj_set_width(ui_CheckboxHead, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CheckboxHead, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CheckboxHead, 77);
    lv_obj_set_y(ui_CheckboxHead, -102);
    lv_obj_set_align(ui_CheckboxHead, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CheckboxHead, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_SliderSpeed = lv_slider_create(ui_ScreenSystem);
    lv_slider_set_range(ui_SliderSpeed, 20, 80);
    lv_slider_set_value(ui_SliderSpeed, 30, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderSpeed) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderSpeed, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderSpeed, 69);
    lv_obj_set_height(ui_SliderSpeed, 10);
    lv_obj_set_x(ui_SliderSpeed, -117);
    lv_obj_set_y(ui_SliderSpeed, -44);
    lv_obj_set_align(ui_SliderSpeed, LV_ALIGN_CENTER);


    ui_Label2 = lv_label_create(ui_ScreenSystem);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 120);
    lv_obj_set_y(ui_Label2, 96);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Back");

    ui_LabelSpeed = lv_label_create(ui_ScreenSystem);
    lv_obj_set_width(ui_LabelSpeed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSpeed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSpeed, -42);
    lv_obj_set_y(ui_LabelSpeed, -45);
    lv_obj_set_align(ui_LabelSpeed, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSpeed, "0.30m/s");

    ui_Button1 = lv_btn_create(ui_ScreenSystem);
    lv_obj_set_width(ui_Button1, 56);
    lv_obj_set_height(ui_Button1, 30);
    lv_obj_set_x(ui_Button1, 46);
    lv_obj_set_y(ui_Button1, 57);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xD599F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_ScreenSystem);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 46);
    lv_obj_set_y(ui_Label3, 57);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Set");

    ui_SliderHeight = lv_slider_create(ui_ScreenSystem);
    lv_slider_set_range(ui_SliderHeight, 20, 99);
    lv_slider_set_value(ui_SliderHeight, 70, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderHeight) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderHeight, 0,
                                                                                                 LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderHeight, 67);
    lv_obj_set_height(ui_SliderHeight, 10);
    lv_obj_set_x(ui_SliderHeight, -116);
    lv_obj_set_y(ui_SliderHeight, 53);
    lv_obj_set_align(ui_SliderHeight, LV_ALIGN_CENTER);


    ui_LabelHeight = lv_label_create(ui_ScreenSystem);
    lv_obj_set_width(ui_LabelHeight, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHeight, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHeight, -41);
    lv_obj_set_y(ui_LabelHeight, 51);
    lv_obj_set_align(ui_LabelHeight, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHeight, "H=70%");

    ui_CheckboxSW = lv_checkbox_create(ui_ScreenSystem);
    lv_checkbox_set_text(ui_CheckboxSW, "Auto Stop Mode");
    lv_obj_set_width(ui_CheckboxSW, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CheckboxSW, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CheckboxSW, 76);
    lv_obj_set_y(ui_CheckboxSW, -75);
    lv_obj_set_align(ui_CheckboxSW, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_CheckboxSW, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_CheckboxSW, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_ButtonJointLeg = lv_btn_create(ui_ScreenSystem);
    lv_obj_set_width(ui_ButtonJointLeg, 70);
    lv_obj_set_height(ui_ButtonJointLeg, 28);
    lv_obj_set_x(ui_ButtonJointLeg, -115);
    lv_obj_set_y(ui_ButtonJointLeg, 96);
    lv_obj_set_align(ui_ButtonJointLeg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonJointLeg, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonJointLeg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonJointLeg, lv_color_hex(0xF3E4E4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonJointLeg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labeljoint = lv_label_create(ui_ScreenSystem);
    lv_obj_set_width(ui_Labeljoint, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labeljoint, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labeljoint, -116);
    lv_obj_set_y(ui_Labeljoint, 96);
    lv_obj_set_align(ui_Labeljoint, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labeljoint, "Leg");
    lv_obj_clear_flag(ui_Labeljoint, LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags

    ui_ButtonJointArm = lv_btn_create(ui_ScreenSystem);
    lv_obj_set_width(ui_ButtonJointArm, 70);
    lv_obj_set_height(ui_ButtonJointArm, 28);
    lv_obj_set_x(ui_ButtonJointArm, -34);
    lv_obj_set_y(ui_ButtonJointArm, 96);
    lv_obj_set_align(ui_ButtonJointArm, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonJointArm, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonJointArm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonJointArm, lv_color_hex(0xF3E4E4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonJointArm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelArm = lv_label_create(ui_ScreenSystem);
    lv_obj_set_width(ui_LabelArm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelArm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelArm, -35);
    lv_obj_set_y(ui_LabelArm, 96);
    lv_obj_set_align(ui_LabelArm, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelArm, "Arm");
    lv_obj_clear_flag(ui_LabelArm, LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags

    ui_ButtonSensor = lv_btn_create(ui_ScreenSystem);
    lv_obj_set_width(ui_ButtonSensor, 70);
    lv_obj_set_height(ui_ButtonSensor, 28);
    lv_obj_set_x(ui_ButtonSensor, 46);
    lv_obj_set_y(ui_ButtonSensor, 96);
    lv_obj_set_align(ui_ButtonSensor, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonSensor, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonSensor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonSensor, lv_color_hex(0xF3E4E4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonSensor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSensor = lv_label_create(ui_ScreenSystem);
    lv_obj_set_width(ui_LabelSensor, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSensor, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSensor, 46);
    lv_obj_set_y(ui_LabelSensor, 96);
    lv_obj_set_align(ui_LabelSensor, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSensor, "Sensor");
    lv_obj_clear_flag(ui_LabelSensor, LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags

    ui_CheckboxSW1 = lv_checkbox_create(ui_ScreenSystem);
    lv_checkbox_set_text(ui_CheckboxSW1, "Auto Start Mode");
    lv_obj_set_width(ui_CheckboxSW1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CheckboxSW1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CheckboxSW1, 76);
    lv_obj_set_y(ui_CheckboxSW1, -45);
    lv_obj_set_align(ui_CheckboxSW1, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_CheckboxSW1, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_CheckboxSW1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_SliderSpeed1 = lv_slider_create(ui_ScreenSystem);
    lv_slider_set_range(ui_SliderSpeed1, 20, 100);
    lv_slider_set_value(ui_SliderSpeed1, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderSpeed1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderSpeed1, 0,
                                                                                                 LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderSpeed1, 69);
    lv_obj_set_height(ui_SliderSpeed1, 10);
    lv_obj_set_x(ui_SliderSpeed1, -117);
    lv_obj_set_y(ui_SliderSpeed1, -12);
    lv_obj_set_align(ui_SliderSpeed1, LV_ALIGN_CENTER);


    ui_LabelRad = lv_label_create(ui_ScreenSystem);
    lv_obj_set_width(ui_LabelRad, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelRad, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelRad, -41);
    lv_obj_set_y(ui_LabelRad, -13);
    lv_obj_set_align(ui_LabelRad, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelRad, "0.20 rad/s");

    ui_Button4 = lv_btn_create(ui_ScreenSystem);
    lv_obj_set_width(ui_Button4, 56);
    lv_obj_set_height(ui_Button4, 30);
    lv_obj_set_x(ui_Button4, 120);
    lv_obj_set_y(ui_Button4, 57);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0xF1E1FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label28 = lv_label_create(ui_ScreenSystem);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label28, 120);
    lv_obj_set_y(ui_Label28, 57);
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, "Save");

    ui_CheckboxSW2 = lv_checkbox_create(ui_ScreenSystem);
    lv_checkbox_set_text(ui_CheckboxSW2, "Collision Avoid");
    lv_obj_set_width(ui_CheckboxSW2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CheckboxSW2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CheckboxSW2, 70);
    lv_obj_set_y(ui_CheckboxSW2, -16);
    lv_obj_set_align(ui_CheckboxSW2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CheckboxSW2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_CheckboxSW3 = lv_checkbox_create(ui_ScreenSystem);
    lv_checkbox_set_text(ui_CheckboxSW3, "Smart Gait Mode");
    lv_obj_set_width(ui_CheckboxSW3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CheckboxSW3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CheckboxSW3, 78);
    lv_obj_set_y(ui_CheckboxSW3, 13);
    lv_obj_set_align(ui_CheckboxSW3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CheckboxSW3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_SliderStep = lv_slider_create(ui_ScreenSystem);
    lv_slider_set_range(ui_SliderStep, 20, 99);
    lv_slider_set_value(ui_SliderStep, 30, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderStep) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderStep, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderStep, 67);
    lv_obj_set_height(ui_SliderStep, 10);
    lv_obj_set_x(ui_SliderStep, -116);
    lv_obj_set_y(ui_SliderStep, 21);
    lv_obj_set_align(ui_SliderStep, LV_ALIGN_CENTER);


    ui_LabelStep = lv_label_create(ui_ScreenSystem);
    lv_obj_set_width(ui_LabelStep, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelStep, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelStep, -42);
    lv_obj_set_y(ui_LabelStep, 20);
    lv_obj_set_align(ui_LabelStep, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelStep, "Step=70%");

    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderSpeed, ui_event_SliderSpeed, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderHeight, ui_event_SliderHeight, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonJointLeg, ui_event_ButtonJointLeg, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonJointArm, ui_event_ButtonJointArm, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonSensor, ui_event_ButtonSensor, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderSpeed1, ui_event_SliderSpeed1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderStep, ui_event_SliderStep, LV_EVENT_ALL, NULL);

}
