// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: ESP32Box

#include "../ui.h"

void ui_ScreenLeg_screen_init(void)
{
    ui_ScreenLeg = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenLeg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenLeg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenLeg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabView3 = lv_tabview_create(ui_ScreenLeg, LV_DIR_TOP, 25);
    lv_obj_set_width(ui_TabView3, 310);
    lv_obj_set_height(ui_TabView3, 167);
    lv_obj_set_x(ui_TabView3, 1);
    lv_obj_set_y(ui_TabView3, 32);
    lv_obj_set_align(ui_TabView3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TabView3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags


    ui_TabPage5 = lv_tabview_add_tab(ui_TabView3, "Robot");

    ui_TabPage6 = lv_tabview_add_tab(ui_TabView3, "Data1");

    ui_TabPage7 = lv_tabview_add_tab(ui_TabView3, "Data2");

    ui_TabPage8 = lv_tabview_add_tab(ui_TabView3, "Data3");

    ui_TabPage1 = lv_tabview_add_tab(ui_TabView3, "Data4");

    ui_ButtonParam1 = lv_btn_create(ui_ScreenLeg);
    lv_obj_set_width(ui_ButtonParam1, 70);
    lv_obj_set_height(ui_ButtonParam1, 28);
    lv_obj_set_x(ui_ButtonParam1, 113);
    lv_obj_set_y(ui_ButtonParam1, -103);
    lv_obj_set_align(ui_ButtonParam1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonParam1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonParam1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonParam1, lv_color_hex(0xF3E4E4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonParam1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonLight1 = lv_btn_create(ui_ScreenLeg);
    lv_obj_set_width(ui_ButtonLight1, 23);
    lv_obj_set_height(ui_ButtonLight1, 18);
    lv_obj_set_x(ui_ButtonLight1, -139);
    lv_obj_set_y(ui_ButtonLight1, -105);
    lv_obj_set_align(ui_ButtonLight1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonLight1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonLight1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonLight1, 55, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_ButtonLight1, lv_color_hex(0xCCCCEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_ButtonLight1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ButtonLight1, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_ScreenLeg);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, 113);
    lv_obj_set_y(ui_Label11, -102);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "Back");
    lv_obj_clear_flag(ui_Label11, LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags

    ui_Label12 = lv_label_create(ui_ScreenLeg);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, -126);
    lv_obj_set_y(ui_Label12, -13);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "Att:");

    ui_LabelL01 = lv_label_create(ui_ScreenLeg);
    lv_obj_set_width(ui_LabelL01, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelL01, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelL01, -60);
    lv_obj_set_y(ui_LabelL01, -14);
    lv_obj_set_align(ui_LabelL01, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelL01, "data1");

    ui_LabelL02 = lv_label_create(ui_ScreenLeg);
    lv_obj_set_width(ui_LabelL02, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelL02, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelL02, 2);
    lv_obj_set_y(ui_LabelL02, -14);
    lv_obj_set_align(ui_LabelL02, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelL02, "data2");

    ui_LabelL03 = lv_label_create(ui_ScreenLeg);
    lv_obj_set_width(ui_LabelL03, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelL03, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelL03, 63);
    lv_obj_set_y(ui_LabelL03, -14);
    lv_obj_set_align(ui_LabelL03, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelL03, "data3");

    ui_Label13 = lv_label_create(ui_ScreenLeg);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, -127);
    lv_obj_set_y(ui_Label13, 11);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "Vel:");

    ui_LabelL11 = lv_label_create(ui_ScreenLeg);
    lv_obj_set_width(ui_LabelL11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelL11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelL11, -60);
    lv_obj_set_y(ui_LabelL11, 11);
    lv_obj_set_align(ui_LabelL11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelL11, "data1");

    ui_LabelL12 = lv_label_create(ui_ScreenLeg);
    lv_obj_set_width(ui_LabelL12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelL12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelL12, 2);
    lv_obj_set_y(ui_LabelL12, 10);
    lv_obj_set_align(ui_LabelL12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelL12, "data2");

    ui_LabelL13 = lv_label_create(ui_ScreenLeg);
    lv_obj_set_width(ui_LabelL13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelL13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelL13, 63);
    lv_obj_set_y(ui_LabelL13, 10);
    lv_obj_set_align(ui_LabelL13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelL13, "data3");

    ui_Label15 = lv_label_create(ui_ScreenLeg);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, -126);
    lv_obj_set_y(ui_Label15, 38);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "Leg_L:");

    ui_LabelL21 = lv_label_create(ui_ScreenLeg);
    lv_obj_set_width(ui_LabelL21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelL21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelL21, -60);
    lv_obj_set_y(ui_LabelL21, 37);
    lv_obj_set_align(ui_LabelL21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelL21, "data1");

    ui_LabelL22 = lv_label_create(ui_ScreenLeg);
    lv_obj_set_width(ui_LabelL22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelL22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelL22, 2);
    lv_obj_set_y(ui_LabelL22, 36);
    lv_obj_set_align(ui_LabelL22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelL22, "data2");

    ui_LabelL23 = lv_label_create(ui_ScreenLeg);
    lv_obj_set_width(ui_LabelL23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelL23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelL23, 63);
    lv_obj_set_y(ui_LabelL23, 36);
    lv_obj_set_align(ui_LabelL23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelL23, "data3");

    ui_Label16 = lv_label_create(ui_ScreenLeg);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, -126);
    lv_obj_set_y(ui_Label16, 83);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "Leg_R:");

    ui_LabelL25 = lv_label_create(ui_ScreenLeg);
    lv_obj_set_width(ui_LabelL25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelL25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelL25, -59);
    lv_obj_set_y(ui_LabelL25, 61);
    lv_obj_set_align(ui_LabelL25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelL25, "data5");

    ui_LabelL26 = lv_label_create(ui_ScreenLeg);
    lv_obj_set_width(ui_LabelL26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelL26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelL26, 3);
    lv_obj_set_y(ui_LabelL26, 61);
    lv_obj_set_align(ui_LabelL26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelL26, "data6");

    ui_LabelL27 = lv_label_create(ui_ScreenLeg);
    lv_obj_set_width(ui_LabelL27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelL27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelL27, 63);
    lv_obj_set_y(ui_LabelL27, 61);
    lv_obj_set_align(ui_LabelL27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelL27, "data7");

    ui_LabelL31 = lv_label_create(ui_ScreenLeg);
    lv_obj_set_width(ui_LabelL31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelL31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelL31, -60);
    lv_obj_set_y(ui_LabelL31, 84);
    lv_obj_set_align(ui_LabelL31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelL31, "data1");

    ui_LabelL32 = lv_label_create(ui_ScreenLeg);
    lv_obj_set_width(ui_LabelL32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelL32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelL32, 3);
    lv_obj_set_y(ui_LabelL32, 84);
    lv_obj_set_align(ui_LabelL32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelL32, "data2");

    ui_LabelL33 = lv_label_create(ui_ScreenLeg);
    lv_obj_set_width(ui_LabelL33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelL33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelL33, 63);
    lv_obj_set_y(ui_LabelL33, 84);
    lv_obj_set_align(ui_LabelL33, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelL33, "data3");

    ui_LabelL35 = lv_label_create(ui_ScreenLeg);
    lv_obj_set_width(ui_LabelL35, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelL35, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelL35, -59);
    lv_obj_set_y(ui_LabelL35, 107);
    lv_obj_set_align(ui_LabelL35, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelL35, "data5");

    ui_LabelL36 = lv_label_create(ui_ScreenLeg);
    lv_obj_set_width(ui_LabelL36, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelL36, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelL36, 3);
    lv_obj_set_y(ui_LabelL36, 107);
    lv_obj_set_align(ui_LabelL36, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelL36, "data6");

    ui_LabelL37 = lv_label_create(ui_ScreenLeg);
    lv_obj_set_width(ui_LabelL37, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelL37, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelL37, 63);
    lv_obj_set_y(ui_LabelL37, 107);
    lv_obj_set_align(ui_LabelL37, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelL37, "data7");

    ui_ButtonCal = lv_btn_create(ui_ScreenLeg);
    lv_obj_set_width(ui_ButtonCal, 70);
    lv_obj_set_height(ui_ButtonCal, 28);
    lv_obj_set_x(ui_ButtonCal, 113);
    lv_obj_set_y(ui_ButtonCal, -69);
    lv_obj_set_align(ui_ButtonCal, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonCal, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonCal, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonCal, lv_color_hex(0xCDFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonCal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelLocal2 = lv_label_create(ui_ScreenLeg);
    lv_obj_set_width(ui_LabelLocal2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelLocal2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelLocal2, 113);
    lv_obj_set_y(ui_LabelLocal2, -68);
    lv_obj_set_align(ui_LabelLocal2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelLocal2, "Cal Leg");

    ui_DropdownCalLeg1 = lv_dropdown_create(ui_ScreenLeg);
    lv_dropdown_set_options(ui_DropdownCalLeg1, "Cal Selet\nCal All\n");
    lv_obj_set_width(ui_DropdownCalLeg1, 106);
    lv_obj_set_height(ui_DropdownCalLeg1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DropdownCalLeg1, -99);
    lv_obj_set_y(ui_DropdownCalLeg1, -72);
    lv_obj_set_align(ui_DropdownCalLeg1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DropdownCalLeg1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_DropdownCalLeg2 = lv_dropdown_create(ui_ScreenLeg);
    lv_dropdown_set_options(ui_DropdownCalLeg2,
                            "JointL0\nJointL1\nJointL2\nJointL3\nJointL4\nJointL5\nJointL6\nJointR0\nJointR1\nJointR2\nJointR3\nJointR4\nJointR5\nJointR6");
    lv_obj_set_width(ui_DropdownCalLeg2, 95);
    lv_obj_set_height(ui_DropdownCalLeg2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DropdownCalLeg2, 15);
    lv_obj_set_y(ui_DropdownCalLeg2, -72);
    lv_obj_set_align(ui_DropdownCalLeg2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DropdownCalLeg2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_LabelL04 = lv_label_create(ui_ScreenLeg);
    lv_obj_set_width(ui_LabelL04, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelL04, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelL04, 124);
    lv_obj_set_y(ui_LabelL04, -15);
    lv_obj_set_align(ui_LabelL04, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelL04, "data4");

    ui_LabelL14 = lv_label_create(ui_ScreenLeg);
    lv_obj_set_width(ui_LabelL14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelL14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelL14, 124);
    lv_obj_set_y(ui_LabelL14, 10);
    lv_obj_set_align(ui_LabelL14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelL14, "data4");

    ui_LabelL24 = lv_label_create(ui_ScreenLeg);
    lv_obj_set_width(ui_LabelL24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelL24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelL24, 124);
    lv_obj_set_y(ui_LabelL24, 35);
    lv_obj_set_align(ui_LabelL24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelL24, "data4");

    ui_LabelL28 = lv_label_create(ui_ScreenLeg);
    lv_obj_set_width(ui_LabelL28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelL28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelL28, 124);
    lv_obj_set_y(ui_LabelL28, 60);
    lv_obj_set_align(ui_LabelL28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelL28, "data8");

    ui_LabelL34 = lv_label_create(ui_ScreenLeg);
    lv_obj_set_width(ui_LabelL34, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelL34, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelL34, 124);
    lv_obj_set_y(ui_LabelL34, 83);
    lv_obj_set_align(ui_LabelL34, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelL34, "data4");

    ui_LabelL38 = lv_label_create(ui_ScreenLeg);
    lv_obj_set_width(ui_LabelL38, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelL38, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelL38, 124);
    lv_obj_set_y(ui_LabelL38, 107);
    lv_obj_set_align(ui_LabelL38, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelL38, "data8");

    ui_LabelLocal3 = lv_label_create(ui_ScreenLeg);
    lv_obj_set_width(ui_LabelLocal3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelLocal3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelLocal3, -33);
    lv_obj_set_y(ui_LabelLocal3, -105);
    lv_obj_set_align(ui_LabelLocal3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelLocal3, "Caliberation Leg Joints");

    lv_obj_add_event_cb(ui_ButtonParam1, ui_event_ButtonParam1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonCal, ui_event_ButtonCal, LV_EVENT_ALL, NULL);

}
