// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: ESP32Box

#include "../ui.h"

void ui_ScreenSensor_screen_init(void)
{
    ui_ScreenSensor = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenSensor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenSensor, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenSensor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabView2 = lv_tabview_create(ui_ScreenSensor, LV_DIR_TOP, 25);
    lv_obj_set_width(ui_TabView2, 310);
    lv_obj_set_height(ui_TabView2, 167);
    lv_obj_set_x(ui_TabView2, 1);
    lv_obj_set_y(ui_TabView2, 32);
    lv_obj_set_align(ui_TabView2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TabView2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags


    ui_TabPage11 = lv_tabview_add_tab(ui_TabView2, "Robot");

    ui_TabPage12 = lv_tabview_add_tab(ui_TabView2, "Data1");

    ui_TabPage13 = lv_tabview_add_tab(ui_TabView2, "Data2");

    ui_TabPage14 = lv_tabview_add_tab(ui_TabView2, "Data3");

    ui_TabPage15 = lv_tabview_add_tab(ui_TabView2, "Data4");

    ui_ButtonParam4 = lv_btn_create(ui_ScreenSensor);
    lv_obj_set_width(ui_ButtonParam4, 70);
    lv_obj_set_height(ui_ButtonParam4, 28);
    lv_obj_set_x(ui_ButtonParam4, 113);
    lv_obj_set_y(ui_ButtonParam4, -103);
    lv_obj_set_align(ui_ButtonParam4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonParam4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonParam4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonParam4, lv_color_hex(0xF3E4E4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonParam4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonLight4 = lv_btn_create(ui_ScreenSensor);
    lv_obj_set_width(ui_ButtonLight4, 23);
    lv_obj_set_height(ui_ButtonLight4, 18);
    lv_obj_set_x(ui_ButtonLight4, -139);
    lv_obj_set_y(ui_ButtonLight4, -105);
    lv_obj_set_align(ui_ButtonLight4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonLight4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonLight4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonLight4, 55, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_ButtonLight4, lv_color_hex(0xCCCCEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_ButtonLight4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ButtonLight4, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label22 = lv_label_create(ui_ScreenSensor);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label22, 113);
    lv_obj_set_y(ui_Label22, -102);
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "Back");
    lv_obj_clear_flag(ui_Label22, LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags

    ui_Label23 = lv_label_create(ui_ScreenSensor);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label23, -126);
    lv_obj_set_y(ui_Label23, -13);
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "Att:");

    ui_LabelS01 = lv_label_create(ui_ScreenSensor);
    lv_obj_set_width(ui_LabelS01, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelS01, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelS01, -59);
    lv_obj_set_y(ui_LabelS01, -14);
    lv_obj_set_align(ui_LabelS01, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelS01, "data1");

    ui_LabelS02 = lv_label_create(ui_ScreenSensor);
    lv_obj_set_width(ui_LabelS02, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelS02, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelS02, 3);
    lv_obj_set_y(ui_LabelS02, -14);
    lv_obj_set_align(ui_LabelS02, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelS02, "data2");

    ui_LabelS03 = lv_label_create(ui_ScreenSensor);
    lv_obj_set_width(ui_LabelS03, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelS03, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelS03, 63);
    lv_obj_set_y(ui_LabelS03, -14);
    lv_obj_set_align(ui_LabelS03, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelS03, "data3");

    ui_Label24 = lv_label_create(ui_ScreenSensor);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label24, -127);
    lv_obj_set_y(ui_Label24, 11);
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "Acc:");

    ui_LabelS11 = lv_label_create(ui_ScreenSensor);
    lv_obj_set_width(ui_LabelS11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelS11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelS11, -59);
    lv_obj_set_y(ui_LabelS11, 12);
    lv_obj_set_align(ui_LabelS11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelS11, "data1");

    ui_LabelS12 = lv_label_create(ui_ScreenSensor);
    lv_obj_set_width(ui_LabelS12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelS12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelS12, 3);
    lv_obj_set_y(ui_LabelS12, 12);
    lv_obj_set_align(ui_LabelS12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelS12, "data2");

    ui_LabelS13 = lv_label_create(ui_ScreenSensor);
    lv_obj_set_width(ui_LabelS13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelS13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelS13, 63);
    lv_obj_set_y(ui_LabelS13, 11);
    lv_obj_set_align(ui_LabelS13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelS13, "data3");

    ui_Label25 = lv_label_create(ui_ScreenSensor);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label25, -126);
    lv_obj_set_y(ui_Label25, 38);
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "Gyro:");

    ui_LabelS21 = lv_label_create(ui_ScreenSensor);
    lv_obj_set_width(ui_LabelS21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelS21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelS21, -59);
    lv_obj_set_y(ui_LabelS21, 39);
    lv_obj_set_align(ui_LabelS21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelS21, "data1");

    ui_LabelS22 = lv_label_create(ui_ScreenSensor);
    lv_obj_set_width(ui_LabelS22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelS22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelS22, 3);
    lv_obj_set_y(ui_LabelS22, 39);
    lv_obj_set_align(ui_LabelS22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelS22, "data2");

    ui_LabelS23 = lv_label_create(ui_ScreenSensor);
    lv_obj_set_width(ui_LabelS23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelS23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelS23, 64);
    lv_obj_set_y(ui_LabelS23, 38);
    lv_obj_set_align(ui_LabelS23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelS23, "data3");

    ui_Label26 = lv_label_create(ui_ScreenSensor);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label26, -126);
    lv_obj_set_y(ui_Label26, 66);
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "Mag:");

    ui_LabelS31 = lv_label_create(ui_ScreenSensor);
    lv_obj_set_width(ui_LabelS31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelS31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelS31, -58);
    lv_obj_set_y(ui_LabelS31, 67);
    lv_obj_set_align(ui_LabelS31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelS31, "data1");

    ui_LabelS32 = lv_label_create(ui_ScreenSensor);
    lv_obj_set_width(ui_LabelS32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelS32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelS32, 3);
    lv_obj_set_y(ui_LabelS32, 67);
    lv_obj_set_align(ui_LabelS32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelS32, "data2");

    ui_LabelS33 = lv_label_create(ui_ScreenSensor);
    lv_obj_set_width(ui_LabelS33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelS33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelS33, 64);
    lv_obj_set_y(ui_LabelS33, 67);
    lv_obj_set_align(ui_LabelS33, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelS33, "data3");

    ui_LabelS41 = lv_label_create(ui_ScreenSensor);
    lv_obj_set_width(ui_LabelS41, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelS41, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelS41, -58);
    lv_obj_set_y(ui_LabelS41, 93);
    lv_obj_set_align(ui_LabelS41, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelS41, "data1");

    ui_LabelS42 = lv_label_create(ui_ScreenSensor);
    lv_obj_set_width(ui_LabelS42, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelS42, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelS42, 4);
    lv_obj_set_y(ui_LabelS42, 93);
    lv_obj_set_align(ui_LabelS42, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelS42, "data2");

    ui_LabelS43 = lv_label_create(ui_ScreenSensor);
    lv_obj_set_width(ui_LabelS43, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelS43, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelS43, 64);
    lv_obj_set_y(ui_LabelS43, 93);
    lv_obj_set_align(ui_LabelS43, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelS43, "data3");

    ui_ButtonCal2 = lv_btn_create(ui_ScreenSensor);
    lv_obj_set_width(ui_ButtonCal2, 70);
    lv_obj_set_height(ui_ButtonCal2, 28);
    lv_obj_set_x(ui_ButtonCal2, 113);
    lv_obj_set_y(ui_ButtonCal2, -69);
    lv_obj_set_align(ui_ButtonCal2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonCal2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonCal2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonCal2, lv_color_hex(0xCDFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonCal2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelLocal1 = lv_label_create(ui_ScreenSensor);
    lv_obj_set_width(ui_LabelLocal1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelLocal1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelLocal1, 113);
    lv_obj_set_y(ui_LabelLocal1, -68);
    lv_obj_set_align(ui_LabelLocal1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelLocal1, "Calibrate");

    ui_DropdownCalSensor = lv_dropdown_create(ui_ScreenSensor);
    lv_dropdown_set_options(ui_DropdownCalSensor, "Cal Acc\nCal Gyro\nCal Baro\nCal Mag");
    lv_obj_set_width(ui_DropdownCalSensor, 105);
    lv_obj_set_height(ui_DropdownCalSensor, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DropdownCalSensor, -100);
    lv_obj_set_y(ui_DropdownCalSensor, -73);
    lv_obj_set_align(ui_DropdownCalSensor, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DropdownCalSensor, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_LabelS04 = lv_label_create(ui_ScreenSensor);
    lv_obj_set_width(ui_LabelS04, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelS04, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelS04, 125);
    lv_obj_set_y(ui_LabelS04, -15);
    lv_obj_set_align(ui_LabelS04, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelS04, "data4");

    ui_LabelS14 = lv_label_create(ui_ScreenSensor);
    lv_obj_set_width(ui_LabelS14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelS14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelS14, 125);
    lv_obj_set_y(ui_LabelS14, 11);
    lv_obj_set_align(ui_LabelS14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelS14, "data4");

    ui_LabelS24 = lv_label_create(ui_ScreenSensor);
    lv_obj_set_width(ui_LabelS24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelS24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelS24, 125);
    lv_obj_set_y(ui_LabelS24, 38);
    lv_obj_set_align(ui_LabelS24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelS24, "data4");

    ui_LabelS34 = lv_label_create(ui_ScreenSensor);
    lv_obj_set_width(ui_LabelS34, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelS34, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelS34, 125);
    lv_obj_set_y(ui_LabelS34, 67);
    lv_obj_set_align(ui_LabelS34, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelS34, "data4");

    ui_LabelS44 = lv_label_create(ui_ScreenSensor);
    lv_obj_set_width(ui_LabelS44, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelS44, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelS44, 125);
    lv_obj_set_y(ui_LabelS44, 93);
    lv_obj_set_align(ui_LabelS44, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelS44, "data4");

    ui_LabelLocal7 = lv_label_create(ui_ScreenSensor);
    lv_obj_set_width(ui_LabelLocal7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelLocal7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelLocal7, -36);
    lv_obj_set_y(ui_LabelLocal7, -105);
    lv_obj_set_align(ui_LabelLocal7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelLocal7, "Caliberation Sensors");

    ui_Label27 = lv_label_create(ui_ScreenSensor);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label27, -126);
    lv_obj_set_y(ui_Label27, 92);
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "Baro:");

    lv_obj_add_event_cb(ui_ButtonParam4, ui_event_ButtonParam4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonCal2, ui_event_ButtonCal2, LV_EVENT_ALL, NULL);

}
