// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: ESP32Box

#include "../ui.h"

void ui_Screenlogin_screen_init(void)
{
    ui_Screenlogin = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screenlogin, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SpinnerLogin = lv_spinner_create(ui_Screenlogin, 1000, 90);
    lv_obj_set_width(ui_SpinnerLogin, 115);
    lv_obj_set_height(ui_SpinnerLogin, 114);
    lv_obj_set_x(ui_SpinnerLogin, 1);
    lv_obj_set_y(ui_SpinnerLogin, -5);
    lv_obj_set_align(ui_SpinnerLogin, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SpinnerLogin, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_blend_mode(ui_SpinnerLogin, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_SpinnerLogin, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Label18 = lv_label_create(ui_Screenlogin);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, 1);
    lv_obj_set_y(ui_Label18, -6);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "Login...");

    // ui_Label19 = lv_label_create(ui_Screenlogin);
    // lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    // lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    // lv_obj_set_x(ui_Label19, 125);
    // lv_obj_set_y(ui_Label19, 101);
    // lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    // lv_label_set_text(ui_Label19, "Next");


}
