// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: ESP32Box

#include "../ui.h"

void ui_ScreenArm_screen_init(void)
{
    ui_ScreenArm = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenArm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenArm, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenArm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabView1 = lv_tabview_create(ui_ScreenArm, LV_DIR_TOP, 25);
    lv_obj_set_width(ui_TabView1, 310);
    lv_obj_set_height(ui_TabView1, 167);
    lv_obj_set_x(ui_TabView1, 1);
    lv_obj_set_y(ui_TabView1, 32);
    lv_obj_set_align(ui_TabView1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TabView1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags


    ui_TabPage2 = lv_tabview_add_tab(ui_TabView1, "Robot");

    ui_TabPage3 = lv_tabview_add_tab(ui_TabView1, "Data1");

    ui_TabPage4 = lv_tabview_add_tab(ui_TabView1, "Data2");

    ui_TabPage9 = lv_tabview_add_tab(ui_TabView1, "Data3");

    ui_TabPage10 = lv_tabview_add_tab(ui_TabView1, "Data4");

    ui_ButtonParam2 = lv_btn_create(ui_ScreenArm);
    lv_obj_set_width(ui_ButtonParam2, 70);
    lv_obj_set_height(ui_ButtonParam2, 28);
    lv_obj_set_x(ui_ButtonParam2, 113);
    lv_obj_set_y(ui_ButtonParam2, -103);
    lv_obj_set_align(ui_ButtonParam2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonParam2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonParam2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonParam2, lv_color_hex(0xF3E4E4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonParam2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonLight2 = lv_btn_create(ui_ScreenArm);
    lv_obj_set_width(ui_ButtonLight2, 23);
    lv_obj_set_height(ui_ButtonLight2, 18);
    lv_obj_set_x(ui_ButtonLight2, -139);
    lv_obj_set_y(ui_ButtonLight2, -105);
    lv_obj_set_align(ui_ButtonLight2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonLight2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonLight2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonLight2, 55, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_ButtonLight2, lv_color_hex(0xCCCCEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_ButtonLight2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ButtonLight2, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_ScreenArm);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 113);
    lv_obj_set_y(ui_Label1, -102);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Back");
    lv_obj_clear_flag(ui_Label1, LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_ScreenArm);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -126);
    lv_obj_set_y(ui_Label4, -13);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Att:");

    ui_LabelA01 = lv_label_create(ui_ScreenArm);
    lv_obj_set_width(ui_LabelA01, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelA01, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelA01, -60);
    lv_obj_set_y(ui_LabelA01, -14);
    lv_obj_set_align(ui_LabelA01, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelA01, "data1");

    ui_LabelA02 = lv_label_create(ui_ScreenArm);
    lv_obj_set_width(ui_LabelA02, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelA02, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelA02, 2);
    lv_obj_set_y(ui_LabelA02, -14);
    lv_obj_set_align(ui_LabelA02, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelA02, "data2");

    ui_LabelA03 = lv_label_create(ui_ScreenArm);
    lv_obj_set_width(ui_LabelA03, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelA03, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelA03, 63);
    lv_obj_set_y(ui_LabelA03, -14);
    lv_obj_set_align(ui_LabelA03, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelA03, "data3");

    ui_Label6 = lv_label_create(ui_ScreenArm);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -127);
    lv_obj_set_y(ui_Label6, 11);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Vel:");

    ui_LabelA11 = lv_label_create(ui_ScreenArm);
    lv_obj_set_width(ui_LabelA11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelA11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelA11, -60);
    lv_obj_set_y(ui_LabelA11, 11);
    lv_obj_set_align(ui_LabelA11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelA11, "data1");

    ui_LabelA12 = lv_label_create(ui_ScreenArm);
    lv_obj_set_width(ui_LabelA12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelA12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelA12, 2);
    lv_obj_set_y(ui_LabelA12, 10);
    lv_obj_set_align(ui_LabelA12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelA12, "data2");

    ui_LabelA13 = lv_label_create(ui_ScreenArm);
    lv_obj_set_width(ui_LabelA13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelA13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelA13, 63);
    lv_obj_set_y(ui_LabelA13, 10);
    lv_obj_set_align(ui_LabelA13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelA13, "data3");

    ui_Label14 = lv_label_create(ui_ScreenArm);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, -126);
    lv_obj_set_y(ui_Label14, 38);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "Arm_L:");

    ui_LabelA21 = lv_label_create(ui_ScreenArm);
    lv_obj_set_width(ui_LabelA21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelA21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelA21, -60);
    lv_obj_set_y(ui_LabelA21, 37);
    lv_obj_set_align(ui_LabelA21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelA21, "data1");

    ui_LabelA22 = lv_label_create(ui_ScreenArm);
    lv_obj_set_width(ui_LabelA22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelA22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelA22, 2);
    lv_obj_set_y(ui_LabelA22, 36);
    lv_obj_set_align(ui_LabelA22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelA22, "data2");

    ui_LabelA23 = lv_label_create(ui_ScreenArm);
    lv_obj_set_width(ui_LabelA23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelA23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelA23, 63);
    lv_obj_set_y(ui_LabelA23, 36);
    lv_obj_set_align(ui_LabelA23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelA23, "data3");

    ui_Label17 = lv_label_create(ui_ScreenArm);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, -126);
    lv_obj_set_y(ui_Label17, 83);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "Arm_R:");

    ui_LabelA25 = lv_label_create(ui_ScreenArm);
    lv_obj_set_width(ui_LabelA25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelA25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelA25, -59);
    lv_obj_set_y(ui_LabelA25, 61);
    lv_obj_set_align(ui_LabelA25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelA25, "data5");

    ui_LabelA26 = lv_label_create(ui_ScreenArm);
    lv_obj_set_width(ui_LabelA26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelA26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelA26, 3);
    lv_obj_set_y(ui_LabelA26, 61);
    lv_obj_set_align(ui_LabelA26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelA26, "data6");

    ui_LabelA27 = lv_label_create(ui_ScreenArm);
    lv_obj_set_width(ui_LabelA27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelA27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelA27, 63);
    lv_obj_set_y(ui_LabelA27, 61);
    lv_obj_set_align(ui_LabelA27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelA27, "data7");

    ui_LabelA31 = lv_label_create(ui_ScreenArm);
    lv_obj_set_width(ui_LabelA31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelA31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelA31, -60);
    lv_obj_set_y(ui_LabelA31, 84);
    lv_obj_set_align(ui_LabelA31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelA31, "data1");

    ui_LabelA32 = lv_label_create(ui_ScreenArm);
    lv_obj_set_width(ui_LabelA32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelA32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelA32, 3);
    lv_obj_set_y(ui_LabelA32, 84);
    lv_obj_set_align(ui_LabelA32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelA32, "data2");

    ui_LabelA33 = lv_label_create(ui_ScreenArm);
    lv_obj_set_width(ui_LabelA33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelA33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelA33, 63);
    lv_obj_set_y(ui_LabelA33, 84);
    lv_obj_set_align(ui_LabelA33, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelA33, "data3");

    ui_LabelA35 = lv_label_create(ui_ScreenArm);
    lv_obj_set_width(ui_LabelA35, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelA35, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelA35, -59);
    lv_obj_set_y(ui_LabelA35, 107);
    lv_obj_set_align(ui_LabelA35, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelA35, "data5");

    ui_LabelA36 = lv_label_create(ui_ScreenArm);
    lv_obj_set_width(ui_LabelA36, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelA36, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelA36, 3);
    lv_obj_set_y(ui_LabelA36, 107);
    lv_obj_set_align(ui_LabelA36, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelA36, "data6");

    ui_LabelA37 = lv_label_create(ui_ScreenArm);
    lv_obj_set_width(ui_LabelA37, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelA37, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelA37, 63);
    lv_obj_set_y(ui_LabelA37, 107);
    lv_obj_set_align(ui_LabelA37, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelA37, "data7");

    ui_ButtonCal1 = lv_btn_create(ui_ScreenArm);
    lv_obj_set_width(ui_ButtonCal1, 70);
    lv_obj_set_height(ui_ButtonCal1, 28);
    lv_obj_set_x(ui_ButtonCal1, 113);
    lv_obj_set_y(ui_ButtonCal1, -69);
    lv_obj_set_align(ui_ButtonCal1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonCal1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonCal1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonCal1, lv_color_hex(0xCDFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonCal1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelLocal4 = lv_label_create(ui_ScreenArm);
    lv_obj_set_width(ui_LabelLocal4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelLocal4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelLocal4, 113);
    lv_obj_set_y(ui_LabelLocal4, -68);
    lv_obj_set_align(ui_LabelLocal4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelLocal4, "Cal Arm");

    ui_DropdownCalArm1 = lv_dropdown_create(ui_ScreenArm);
    lv_dropdown_set_options(ui_DropdownCalArm1, "Cal Selet\nCal All\n");
    lv_obj_set_width(ui_DropdownCalArm1, 105);
    lv_obj_set_height(ui_DropdownCalArm1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DropdownCalArm1, -100);
    lv_obj_set_y(ui_DropdownCalArm1, -73);
    lv_obj_set_align(ui_DropdownCalArm1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DropdownCalArm1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_DropdownCalArm2 = lv_dropdown_create(ui_ScreenArm);
    lv_dropdown_set_options(ui_DropdownCalArm2,
                            "JointL0\nJointL1\nJointL2\nJointL3\nJointL4\nJointL5\nJointL6\nJointR0\nJointR1\nJointR2\nJointR3\nJointR4\nJointR5\nJointR6");
    lv_obj_set_width(ui_DropdownCalArm2, 95);
    lv_obj_set_height(ui_DropdownCalArm2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DropdownCalArm2, 12);
    lv_obj_set_y(ui_DropdownCalArm2, -73);
    lv_obj_set_align(ui_DropdownCalArm2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DropdownCalArm2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_LabelA04 = lv_label_create(ui_ScreenArm);
    lv_obj_set_width(ui_LabelA04, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelA04, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelA04, 124);
    lv_obj_set_y(ui_LabelA04, -15);
    lv_obj_set_align(ui_LabelA04, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelA04, "data4");

    ui_LabelA14 = lv_label_create(ui_ScreenArm);
    lv_obj_set_width(ui_LabelA14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelA14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelA14, 124);
    lv_obj_set_y(ui_LabelA14, 10);
    lv_obj_set_align(ui_LabelA14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelA14, "data4");

    ui_LabelA24 = lv_label_create(ui_ScreenArm);
    lv_obj_set_width(ui_LabelA24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelA24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelA24, 124);
    lv_obj_set_y(ui_LabelA24, 35);
    lv_obj_set_align(ui_LabelA24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelA24, "data4");

    ui_LabelA28 = lv_label_create(ui_ScreenArm);
    lv_obj_set_width(ui_LabelA28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelA28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelA28, 124);
    lv_obj_set_y(ui_LabelA28, 60);
    lv_obj_set_align(ui_LabelA28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelA28, "data8");

    ui_LabelA34 = lv_label_create(ui_ScreenArm);
    lv_obj_set_width(ui_LabelA34, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelA34, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelA34, 124);
    lv_obj_set_y(ui_LabelA34, 83);
    lv_obj_set_align(ui_LabelA34, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelA34, "data4");

    ui_LabelA38 = lv_label_create(ui_ScreenArm);
    lv_obj_set_width(ui_LabelA38, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelA38, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelA38, 124);
    lv_obj_set_y(ui_LabelA38, 107);
    lv_obj_set_align(ui_LabelA38, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelA38, "data8");

    ui_LabelLocal6 = lv_label_create(ui_ScreenArm);
    lv_obj_set_width(ui_LabelLocal6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelLocal6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelLocal6, -33);
    lv_obj_set_y(ui_LabelLocal6, -105);
    lv_obj_set_align(ui_LabelLocal6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelLocal6, "Caliberation Arm Joints");

    lv_obj_add_event_cb(ui_ButtonParam2, ui_event_ButtonParam2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonCal1, ui_event_ButtonCal1, LV_EVENT_ALL, NULL);

}
