// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: ESP32Box

#include "../ui.h"

void ui_ScreenMission_screen_init(void)
{
    ui_ScreenMission = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenMission, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenMission, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenMission, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonParam8 = lv_btn_create(ui_ScreenMission);
    lv_obj_set_width(ui_ButtonParam8, 70);
    lv_obj_set_height(ui_ButtonParam8, 28);
    lv_obj_set_x(ui_ButtonParam8, 117);
    lv_obj_set_y(ui_ButtonParam8, -103);
    lv_obj_set_align(ui_ButtonParam8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonParam8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonParam8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonParam8, lv_color_hex(0xF3E4E4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonParam8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label32 = lv_label_create(ui_ButtonParam8);
    lv_obj_set_width(ui_Label32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label32, 1);
    lv_obj_set_y(ui_Label32, -1);
    lv_obj_set_align(ui_Label32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label32, "Back");
    lv_obj_clear_flag(ui_Label32, LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_obj_set_style_text_color(ui_Label32, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label32, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelLocal9 = lv_label_create(ui_ScreenMission);
    lv_obj_set_width(ui_LabelLocal9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelLocal9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelLocal9, -102);
    lv_obj_set_y(ui_LabelLocal9, -104);
    lv_obj_set_align(ui_LabelLocal9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelLocal9, "SLAM:");

    ui_LabelIP2 = lv_label_create(ui_ScreenMission);
    lv_obj_set_width(ui_LabelIP2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelIP2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelIP2, -5);
    lv_obj_set_y(ui_LabelIP2, -105);
    lv_obj_set_align(ui_LabelIP2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelIP2, "System Disconnect");

    ui_ButtonLight6 = lv_btn_create(ui_ScreenMission);
    lv_obj_set_width(ui_ButtonLight6, 23);
    lv_obj_set_height(ui_ButtonLight6, 18);
    lv_obj_set_x(ui_ButtonLight6, -139);
    lv_obj_set_y(ui_ButtonLight6, -105);
    lv_obj_set_align(ui_ButtonLight6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonLight6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonLight6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonLight6, 55, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_ButtonLight6, lv_color_hex(0xCCCCEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_ButtonLight6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ButtonLight6, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_ScreenMission);
    lv_obj_set_width(ui_Panel5, 218);
    lv_obj_set_height(ui_Panel5, 160);
    lv_obj_set_x(ui_Panel5, -40);
    lv_obj_set_y(ui_Panel5, -1);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image3 = lv_img_create(ui_Panel5);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image3, -1);
    lv_obj_set_y(ui_Image3, -3);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SwitchVideo = lv_switch_create(ui_ScreenMission);
    lv_obj_set_width(ui_SwitchVideo, 50);
    lv_obj_set_height(ui_SwitchVideo, 16);
    lv_obj_set_x(ui_SwitchVideo, 114);
    lv_obj_set_y(ui_SwitchVideo, -44);
    lv_obj_set_align(ui_SwitchVideo, LV_ALIGN_CENTER);


    ui_Label36 = lv_label_create(ui_ScreenMission);
    lv_obj_set_width(ui_Label36, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label36, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label36, 114);
    lv_obj_set_y(ui_Label36, -67);
    lv_obj_set_align(ui_Label36, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label36, "Video");

    ui_ButtonParam12 = lv_btn_create(ui_ScreenMission);
    lv_obj_set_width(ui_ButtonParam12, 78);
    lv_obj_set_height(ui_ButtonParam12, 28);
    lv_obj_set_x(ui_ButtonParam12, -111);
    lv_obj_set_y(ui_ButtonParam12, 100);
    lv_obj_set_align(ui_ButtonParam12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonParam12, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonParam12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonParam12, lv_color_hex(0xF3E4E4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonParam12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label37 = lv_label_create(ui_ButtonParam12);
    lv_obj_set_width(ui_Label37, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label37, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label37, 1);
    lv_obj_set_y(ui_Label37, -1);
    lv_obj_set_align(ui_Label37, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label37, "Home");
    lv_obj_clear_flag(ui_Label37, LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_obj_set_style_text_color(ui_Label37, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label37, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonParam13 = lv_btn_create(ui_ScreenMission);
    lv_obj_set_width(ui_ButtonParam13, 78);
    lv_obj_set_height(ui_ButtonParam13, 28);
    lv_obj_set_x(ui_ButtonParam13, 115);
    lv_obj_set_y(ui_ButtonParam13, 100);
    lv_obj_set_align(ui_ButtonParam13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonParam13, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonParam13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonParam13, lv_color_hex(0xC90000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonParam13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label38 = lv_label_create(ui_ButtonParam13);
    lv_obj_set_width(ui_Label38, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label38, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label38, 1);
    lv_obj_set_y(ui_Label38, -1);
    lv_obj_set_align(ui_Label38, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label38, "Stop");
    lv_obj_clear_flag(ui_Label38, LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_obj_set_style_text_color(ui_Label38, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label38, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonParam14 = lv_btn_create(ui_ScreenMission);
    lv_obj_set_width(ui_ButtonParam14, 119);
    lv_obj_set_height(ui_ButtonParam14, 28);
    lv_obj_set_x(ui_ButtonParam14, 1);
    lv_obj_set_y(ui_ButtonParam14, 100);
    lv_obj_set_align(ui_ButtonParam14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonParam14, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonParam14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonParam14, lv_color_hex(0xF3E4E4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonParam14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label39 = lv_label_create(ui_ButtonParam14);
    lv_obj_set_width(ui_Label39, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label39, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label39, 1);
    lv_obj_set_y(ui_Label39, -1);
    lv_obj_set_align(ui_Label39, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label39, "WayPoint");
    lv_obj_clear_flag(ui_Label39, LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_obj_set_style_text_color(ui_Label39, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label39, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RollerWaypoints = lv_roller_create(ui_ScreenMission);
    lv_roller_set_options(ui_RollerWaypoints, "P0\nP1\nP2\nP3\nP4\nP5\nP6\nP7\nP8\nP9", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_RollerWaypoints, 63);
    lv_obj_set_height(ui_RollerWaypoints, 98);
    lv_obj_set_x(ui_RollerWaypoints, 114);
    lv_obj_set_y(ui_RollerWaypoints, 25);
    lv_obj_set_align(ui_RollerWaypoints, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_ButtonParam8, ui_event_ButtonParam8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonParam12, ui_event_ButtonParam12, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonParam13, ui_event_ButtonParam13, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonParam14, ui_event_ButtonParam14, LV_EVENT_ALL, NULL);

}
