// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: ESP32Box

#include "../ui.h"

void ui_ScreenWifi_screen_init(void)
{
    ui_ScreenWifi = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenWifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_KeyboardWifi = lv_keyboard_create(ui_ScreenWifi);
    lv_keyboard_set_mode(ui_KeyboardWifi, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_KeyboardWifi, 310);
    lv_obj_set_height(ui_KeyboardWifi, 120);
    lv_obj_set_x(ui_KeyboardWifi, 0);
    lv_obj_set_y(ui_KeyboardWifi, 56);
    lv_obj_set_align(ui_KeyboardWifi, LV_ALIGN_CENTER);

    ui_Label7 = lv_label_create(ui_ScreenWifi);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -114);
    lv_obj_set_y(ui_Label7, -100);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Robot Wifi:");

    ui_Label8 = lv_label_create(ui_ScreenWifi);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -119);
    lv_obj_set_y(ui_Label8, -26);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Target IP:");

    ui_TextAreaIP = lv_textarea_create(ui_ScreenWifi);
    lv_obj_set_width(ui_TextAreaIP, 150);
    lv_obj_set_height(ui_TextAreaIP, LV_SIZE_CONTENT);    /// 31
    lv_obj_set_x(ui_TextAreaIP, 11);
    lv_obj_set_y(ui_TextAreaIP, -24);
    lv_obj_set_align(ui_TextAreaIP, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_TextAreaIP, 20);
    lv_textarea_set_text(ui_TextAreaIP, "192.168.1.3");
    lv_textarea_set_placeholder_text(ui_TextAreaIP, "Placeholder...");
    lv_textarea_set_one_line(ui_TextAreaIP, true);



    ui_Label9 = lv_label_create(ui_ScreenWifi);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, -117);
    lv_obj_set_y(ui_Label9, -63);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "Password:");

    ui_TextAreaPwd = lv_textarea_create(ui_ScreenWifi);
    lv_obj_set_width(ui_TextAreaPwd, 150);
    lv_obj_set_height(ui_TextAreaPwd, LV_SIZE_CONTENT);    /// 31
    lv_obj_set_x(ui_TextAreaPwd, 11);
    lv_obj_set_y(ui_TextAreaPwd, -63);
    lv_obj_set_align(ui_TextAreaPwd, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_TextAreaPwd, 8);
    lv_textarea_set_text(ui_TextAreaPwd, "11111111");
    lv_textarea_set_placeholder_text(ui_TextAreaPwd, "Placeholder...");
    lv_textarea_set_one_line(ui_TextAreaPwd, true);
    lv_textarea_set_password_mode(ui_TextAreaPwd, true);



    ui_ButtonLogin = lv_btn_create(ui_ScreenWifi);
    lv_obj_set_width(ui_ButtonLogin, 58);
    lv_obj_set_height(ui_ButtonLogin, 104);
    lv_obj_set_x(ui_ButtonLogin, 123);
    lv_obj_set_y(ui_ButtonLogin, -63);
    lv_obj_set_align(ui_ButtonLogin, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonLogin, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonLogin, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonLogin, lv_color_hex(0xE3C7C7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonLogin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_ScreenWifi);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 123);
    lv_obj_set_y(ui_Label10, -63);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "Login");

    ui_DropdownRobotSel = lv_dropdown_create(ui_ScreenWifi);
    lv_dropdown_set_options(ui_DropdownRobotSel, "0\n1\n2\n3\n4\n5\n6\n7\n8\n9\n10");
    lv_obj_set_width(ui_DropdownRobotSel, 51);
    lv_obj_set_height(ui_DropdownRobotSel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DropdownRobotSel, 59);
    lv_obj_set_y(ui_DropdownRobotSel, -101);
    lv_obj_set_align(ui_DropdownRobotSel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DropdownRobotSel, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_DropdownRobot = lv_dropdown_create(ui_ScreenWifi);
    lv_dropdown_set_options(ui_DropdownRobot, "Tinker-\nButler-\nQLoong-\nWLoong-");
    lv_obj_set_width(ui_DropdownRobot, 88);
    lv_obj_set_height(ui_DropdownRobot, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DropdownRobot, -19);
    lv_obj_set_y(ui_DropdownRobot, -101);
    lv_obj_set_align(ui_DropdownRobot, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DropdownRobot, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    lv_obj_add_event_cb(ui_KeyboardWifi, ui_event_KeyboardWifi, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextAreaIP, ui_event_TextAreaIP, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextAreaPwd, ui_event_TextAreaPwd, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonLogin, ui_event_ButtonLogin, LV_EVENT_ALL, NULL);

}
