// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: ESP32Box

#include "../ui.h"

void ui_ScreenloginFail_screen_init(void)
{
    ui_ScreenloginFail = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenloginFail, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenloginFail, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenloginFail, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label40 = lv_label_create(ui_ScreenloginFail);
    lv_obj_set_width(ui_Label40, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label40, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label40, 1);
    lv_obj_set_y(ui_Label40, 49);
    lv_obj_set_align(ui_Label40, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label40, "Failed Connect to Robot !");

    ui_Button2 = lv_btn_create(ui_ScreenloginFail);
    lv_obj_set_width(ui_Button2, 47);
    lv_obj_set_height(ui_Button2, 25);
    lv_obj_set_x(ui_Button2, 125);
    lv_obj_set_y(ui_Button2, 99);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0xE6D4D4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label19 = lv_label_create(ui_ScreenloginFail);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, 125);
    lv_obj_set_y(ui_Label19, 101);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "Next");

    ui_Image5 = lv_img_create(ui_ScreenloginFail);
    lv_img_set_src(ui_Image5, &ui_img_1700300519);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 131
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 106
    lv_obj_set_x(ui_Image5, -1);
    lv_obj_set_y(ui_Image5, -11);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image5, 200);

    ui_Button5 = lv_btn_create(ui_ScreenloginFail);
    lv_obj_set_width(ui_Button5, 47);
    lv_obj_set_height(ui_Button5, 25);
    lv_obj_set_x(ui_Button5, -125);
    lv_obj_set_y(ui_Button5, 99);
    lv_obj_set_align(ui_Button5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button5, lv_color_hex(0xE6D4D4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label41 = lv_label_create(ui_ScreenloginFail);
    lv_obj_set_width(ui_Label41, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label41, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label41, -124);
    lv_obj_set_y(ui_Label41, 100);
    lv_obj_set_align(ui_Label41, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label41, "Back");

    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Label41, ui_event_Label41, LV_EVENT_ALL, NULL);

}
