// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: ESP32Box

#include "../ui.h"

void ui_ScreenRC_screen_init(void)
{
    ui_ScreenRC = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenRC, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenRC, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenRC, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonParam = lv_btn_create(ui_ScreenRC);
    lv_obj_set_width(ui_ButtonParam, 70);
    lv_obj_set_height(ui_ButtonParam, 28);
    lv_obj_set_x(ui_ButtonParam, 113);
    lv_obj_set_y(ui_ButtonParam, -64);
    lv_obj_set_align(ui_ButtonParam, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonParam, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonParam, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonParam, lv_color_hex(0xF3E4E4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonParam, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label = lv_label_create(ui_ButtonParam);
    lv_obj_set_width(ui_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label, 0);
    lv_obj_set_y(ui_Label, 1);
    lv_obj_set_align(ui_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label, "System");
    lv_obj_clear_flag(ui_Label, LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_obj_set_style_text_color(ui_Label, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwitchAuto = lv_switch_create(ui_ScreenRC);
    lv_obj_set_width(ui_SwitchAuto, 37);
    lv_obj_set_height(ui_SwitchAuto, 20);
    lv_obj_set_x(ui_SwitchAuto, 130);
    lv_obj_set_y(ui_SwitchAuto, -99);
    lv_obj_set_align(ui_SwitchAuto, LV_ALIGN_CENTER);


    ui_LabelIP = lv_label_create(ui_ScreenRC);
    lv_obj_set_width(ui_LabelIP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelIP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelIP, 0);
    lv_obj_set_y(ui_LabelIP, -104);
    lv_obj_set_align(ui_LabelIP, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelIP, "192.168.1.130");

    ui_LabelLocal = lv_label_create(ui_ScreenRC);
    lv_obj_set_width(ui_LabelLocal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelLocal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelLocal, -89);
    lv_obj_set_y(ui_LabelLocal, -104);
    lv_obj_set_align(ui_LabelLocal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelLocal, "Local IP:");

    ui_ButtonLight = lv_btn_create(ui_ScreenRC);
    lv_obj_set_width(ui_ButtonLight, 23);
    lv_obj_set_height(ui_ButtonLight, 18);
    lv_obj_set_x(ui_ButtonLight, -139);
    lv_obj_set_y(ui_ButtonLight, -105);
    lv_obj_set_align(ui_ButtonLight, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonLight, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonLight, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonLight, 55, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_ButtonLight, lv_color_hex(0xCCCCEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_ButtonLight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ButtonLight, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonPower = lv_btn_create(ui_ScreenRC);
    lv_obj_set_width(ui_ButtonPower, 70);
    lv_obj_set_height(ui_ButtonPower, 35);
    lv_obj_set_x(ui_ButtonPower, 113);
    lv_obj_set_y(ui_ButtonPower, 90);
    lv_obj_set_align(ui_ButtonPower, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonPower, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonPower, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonPower, lv_color_hex(0xFF3333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonPower, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPower = lv_label_create(ui_ButtonPower);
    lv_obj_set_width(ui_LabelPower, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPower, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPower, 1);
    lv_obj_set_y(ui_LabelPower, 1);
    lv_obj_set_align(ui_LabelPower, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPower, "Power");

    ui_LabelMode = lv_label_create(ui_ScreenRC);
    lv_obj_set_width(ui_LabelMode, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMode, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMode, -127);
    lv_obj_set_y(ui_LabelMode, -81);
    lv_obj_set_align(ui_LabelMode, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMode, "Mode:");

    ui_LabelGPTshow = lv_label_create(ui_ScreenRC);
    lv_obj_set_width(ui_LabelGPTshow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelGPTshow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelGPTshow, 36);
    lv_obj_set_y(ui_LabelGPTshow, -81);
    lv_obj_set_align(ui_LabelGPTshow, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelGPTshow, "Null");

    ui_LabelGPT = lv_label_create(ui_ScreenRC);
    lv_obj_set_width(ui_LabelGPT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelGPT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelGPT, -15);
    lv_obj_set_y(ui_LabelGPT, -81);
    lv_obj_set_align(ui_LabelGPT, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelGPT, "System:");

    ui_LabelMShow = lv_label_create(ui_ScreenRC);
    lv_obj_set_width(ui_LabelMShow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMShow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMShow, -75);
    lv_obj_set_y(ui_LabelMShow, -81);
    lv_obj_set_align(ui_LabelMShow, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMShow, "Idle");

    ui_LabelAuto = lv_label_create(ui_ScreenRC);
    lv_obj_set_width(ui_LabelAuto, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelAuto, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelAuto, 83);
    lv_obj_set_y(ui_LabelAuto, -99);
    lv_obj_set_align(ui_LabelAuto, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelAuto, "Auto:");

    ui_ButtonJointArm1 = lv_btn_create(ui_ScreenRC);
    lv_obj_set_width(ui_ButtonJointArm1, 70);
    lv_obj_set_height(ui_ButtonJointArm1, 28);
    lv_obj_set_x(ui_ButtonJointArm1, 113);
    lv_obj_set_y(ui_ButtonJointArm1, -28);
    lv_obj_set_align(ui_ButtonJointArm1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonJointArm1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonJointArm1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonJointArm1, lv_color_hex(0xF3E4E4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonJointArm1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelGPT1 = lv_label_create(ui_ButtonJointArm1);
    lv_obj_set_width(ui_LabelGPT1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelGPT1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelGPT1, -1);
    lv_obj_set_y(ui_LabelGPT1, 1);
    lv_obj_set_align(ui_LabelGPT1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelGPT1, "ChatGPT");
    lv_obj_clear_flag(ui_LabelGPT1, LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_obj_set_style_text_color(ui_LabelGPT1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelGPT1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonJointArm2 = lv_btn_create(ui_ScreenRC);
    lv_obj_set_width(ui_ButtonJointArm2, 70);
    lv_obj_set_height(ui_ButtonJointArm2, 28);
    lv_obj_set_x(ui_ButtonJointArm2, 114);
    lv_obj_set_y(ui_ButtonJointArm2, 10);
    lv_obj_set_align(ui_ButtonJointArm2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonJointArm2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonJointArm2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonJointArm2, lv_color_hex(0xF3E4E4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonJointArm2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMisson = lv_label_create(ui_ButtonJointArm2);
    lv_obj_set_width(ui_LabelMisson, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMisson, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMisson, -1);
    lv_obj_set_y(ui_LabelMisson, 1);
    lv_obj_set_align(ui_LabelMisson, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMisson, "MIssion");
    lv_obj_clear_flag(ui_LabelMisson, LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_obj_set_style_text_color(ui_LabelMisson, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMisson, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonJointArm3 = lv_btn_create(ui_ScreenRC);
    lv_obj_set_width(ui_ButtonJointArm3, 70);
    lv_obj_set_height(ui_ButtonJointArm3, 28);
    lv_obj_set_x(ui_ButtonJointArm3, 114);
    lv_obj_set_y(ui_ButtonJointArm3, 47);
    lv_obj_set_align(ui_ButtonJointArm3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonJointArm3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonJointArm3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonJointArm3, lv_color_hex(0xF3E4E4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonJointArm3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelGPT3 = lv_label_create(ui_ButtonJointArm3);
    lv_obj_set_width(ui_LabelGPT3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelGPT3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelGPT3, -1);
    lv_obj_set_y(ui_LabelGPT3, 1);
    lv_obj_set_align(ui_LabelGPT3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelGPT3, "Act Edit");
    lv_obj_clear_flag(ui_LabelGPT3, LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_obj_set_style_text_color(ui_LabelGPT3, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelGPT3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageButtonRC = lv_img_create(ui_ScreenRC);
    lv_img_set_src(ui_ImageButtonRC, &ui_img_btn_pad_bottom_png);
    lv_obj_set_width(ui_ImageButtonRC, LV_SIZE_CONTENT);   /// 170
    lv_obj_set_height(ui_ImageButtonRC, LV_SIZE_CONTENT);    /// 170
    lv_obj_set_x(ui_ImageButtonRC, -48);
    lv_obj_set_y(ui_ImageButtonRC, 19);
    lv_obj_set_align(ui_ImageButtonRC, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageButtonRC, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageButtonRC, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImageButtonRC, 140);

    ui_PanelRight = lv_obj_create(ui_ImageButtonRC);
    lv_obj_set_width(ui_PanelRight, 38);
    lv_obj_set_height(ui_PanelRight, 66);
    lv_obj_set_x(ui_PanelRight, 52);
    lv_obj_set_y(ui_PanelRight, 1);
    lv_obj_set_align(ui_PanelRight, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelRight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelRight, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelRight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelRight, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelRight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelRight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelUp = lv_obj_create(ui_ImageButtonRC);
    lv_obj_set_width(ui_PanelUp, 66);
    lv_obj_set_height(ui_PanelUp, 36);
    lv_obj_set_x(ui_PanelUp, 0);
    lv_obj_set_y(ui_PanelUp, -50);
    lv_obj_set_align(ui_PanelUp, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelUp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelUp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelUp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelUp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelUp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelUp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelDown = lv_obj_create(ui_ImageButtonRC);
    lv_obj_set_width(ui_PanelDown, 66);
    lv_obj_set_height(ui_PanelDown, 34);
    lv_obj_set_x(ui_PanelDown, 1);
    lv_obj_set_y(ui_PanelDown, 54);
    lv_obj_set_align(ui_PanelDown, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelDown, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelDown, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelDown, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelDown, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelDown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelDown, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelMid = lv_obj_create(ui_ImageButtonRC);
    lv_obj_set_width(ui_PanelMid, 32);
    lv_obj_set_height(ui_PanelMid, 31);
    lv_obj_set_x(ui_PanelMid, 1);
    lv_obj_set_y(ui_PanelMid, 1);
    lv_obj_set_align(ui_PanelMid, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelMid, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_PanelMid, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelMid, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelLeft = lv_obj_create(ui_ImageButtonRC);
    lv_obj_set_width(ui_PanelLeft, 37);
    lv_obj_set_height(ui_PanelLeft, 66);
    lv_obj_set_x(ui_PanelLeft, -53);
    lv_obj_set_y(ui_PanelLeft, 1);
    lv_obj_set_align(ui_PanelLeft, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelLeft, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelLeft, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelLeft, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelLeft, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelLeft, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelLeft, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageButtonRC2 = lv_img_create(ui_ImageButtonRC);
    lv_img_set_src(ui_ImageButtonRC2, &ui_img_btn_pad_top_png);
    lv_obj_set_width(ui_ImageButtonRC2, LV_SIZE_CONTENT);   /// 242
    lv_obj_set_height(ui_ImageButtonRC2, LV_SIZE_CONTENT);    /// 237
    lv_obj_set_align(ui_ImageButtonRC2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageButtonRC2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageButtonRC2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImageButtonRC2, 140);
    lv_obj_set_style_img_recolor(ui_ImageButtonRC2, lv_color_hex(0xEF1E1E), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_img_recolor_opa(ui_ImageButtonRC2, 100, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_ArrowDown = lv_img_create(ui_ImageButtonRC2);
    lv_img_set_src(ui_ArrowDown, &ui_img_arrow_down_png);
    lv_obj_set_width(ui_ArrowDown, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_ArrowDown, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_ArrowDown, 0);
    lv_obj_set_y(ui_ArrowDown, 46);
    lv_obj_set_align(ui_ArrowDown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ArrowDown, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ArrowDown, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_ArrowDown, lv_color_hex(0xBA0C0C), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_img_recolor_opa(ui_ArrowDown, 100, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_ArrowUp = lv_img_create(ui_ImageButtonRC2);
    lv_img_set_src(ui_ArrowUp, &ui_img_arrow_up_png);
    lv_obj_set_width(ui_ArrowUp, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_ArrowUp, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_ArrowUp, 0);
    lv_obj_set_y(ui_ArrowUp, -44);
    lv_obj_set_align(ui_ArrowUp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ArrowUp, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ArrowUp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_ArrowUp, lv_color_hex(0xBD0202), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_img_recolor_opa(ui_ArrowUp, 100, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_ArrowRight = lv_img_create(ui_ImageButtonRC2);
    lv_img_set_src(ui_ArrowRight, &ui_img_arrow_right_png);
    lv_obj_set_width(ui_ArrowRight, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_ArrowRight, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_ArrowRight, 46);
    lv_obj_set_y(ui_ArrowRight, 1);
    lv_obj_set_align(ui_ArrowRight, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ArrowRight, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ArrowRight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_ArrowRight, lv_color_hex(0xAB001F), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_img_recolor_opa(ui_ArrowRight, 100, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_ArrowLeft = lv_img_create(ui_ImageButtonRC2);
    lv_img_set_src(ui_ArrowLeft, &ui_img_arrow_left_png);
    lv_obj_set_width(ui_ArrowLeft, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_ArrowLeft, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_ArrowLeft, -46);
    lv_obj_set_y(ui_ArrowLeft, 2);
    lv_obj_set_align(ui_ArrowLeft, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ArrowLeft, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ArrowLeft, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_ArrowLeft, lv_color_hex(0xEE0000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_img_recolor_opa(ui_ArrowLeft, 100, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_ImageButton0 = lv_img_create(ui_ScreenRC);
    lv_img_set_src(ui_ImageButton0, &ui_img_btn_main_off_png);
    lv_obj_set_width(ui_ImageButton0, LV_SIZE_CONTENT);   /// 160
    lv_obj_set_height(ui_ImageButton0, LV_SIZE_CONTENT);    /// 65
    lv_obj_set_x(ui_ImageButton0, 22);
    lv_obj_set_y(ui_ImageButton0, -49);
    lv_obj_set_align(ui_ImageButton0, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageButton0, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageButton0, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_ImageButton0, 450);
    lv_img_set_zoom(ui_ImageButton0, 90);
    lv_obj_set_style_img_recolor(ui_ImageButton0, lv_color_hex(0xB10C0C), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_img_recolor_opa(ui_ImageButton0, 150, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Panel1 = lv_obj_create(ui_ImageButton0);
    lv_obj_set_width(ui_Panel1, 40);
    lv_obj_set_height(ui_Panel1, 41);
    lv_obj_set_x(ui_Panel1, 2);
    lv_obj_set_y(ui_Panel1, -1);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageButton1 = lv_img_create(ui_ScreenRC);
    lv_img_set_src(ui_ImageButton1, &ui_img_btn_main_off_png);
    lv_obj_set_width(ui_ImageButton1, LV_SIZE_CONTENT);   /// 160
    lv_obj_set_height(ui_ImageButton1, LV_SIZE_CONTENT);    /// 65
    lv_obj_set_x(ui_ImageButton1, 21);
    lv_obj_set_y(ui_ImageButton1, 88);
    lv_obj_set_align(ui_ImageButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageButton1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_ImageButton1, -450);
    lv_img_set_zoom(ui_ImageButton1, 90);
    lv_obj_set_style_img_recolor(ui_ImageButton1, lv_color_hex(0xB10C0C), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_img_recolor_opa(ui_ImageButton1, 150, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Panel2 = lv_obj_create(ui_ImageButton1);
    lv_obj_set_width(ui_Panel2, 40);
    lv_obj_set_height(ui_Panel2, 41);
    lv_obj_set_x(ui_Panel2, 2);
    lv_obj_set_y(ui_Panel2, -1);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageButton2 = lv_img_create(ui_ScreenRC);
    lv_img_set_src(ui_ImageButton2, &ui_img_btn_main_off_png);
    lv_obj_set_width(ui_ImageButton2, LV_SIZE_CONTENT);   /// 160
    lv_obj_set_height(ui_ImageButton2, LV_SIZE_CONTENT);    /// 65
    lv_obj_set_x(ui_ImageButton2, -118);
    lv_obj_set_y(ui_ImageButton2, 87);
    lv_obj_set_align(ui_ImageButton2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageButton2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageButton2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_ImageButton2, 450);
    lv_img_set_zoom(ui_ImageButton2, 90);
    lv_obj_set_style_img_recolor(ui_ImageButton2, lv_color_hex(0xB10C0C), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_img_recolor_opa(ui_ImageButton2, 150, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Panel3 = lv_obj_create(ui_ImageButton2);
    lv_obj_set_width(ui_Panel3, 40);
    lv_obj_set_height(ui_Panel3, 41);
    lv_obj_set_x(ui_Panel3, 2);
    lv_obj_set_y(ui_Panel3, -1);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageButton3 = lv_img_create(ui_ScreenRC);
    lv_img_set_src(ui_ImageButton3, &ui_img_btn_main_off_png);
    lv_obj_set_width(ui_ImageButton3, LV_SIZE_CONTENT);   /// 160
    lv_obj_set_height(ui_ImageButton3, LV_SIZE_CONTENT);    /// 65
    lv_obj_set_x(ui_ImageButton3, -120);
    lv_obj_set_y(ui_ImageButton3, -47);
    lv_obj_set_align(ui_ImageButton3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageButton3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageButton3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_ImageButton3, -450);
    lv_img_set_zoom(ui_ImageButton3, 90);
    lv_obj_set_style_img_recolor(ui_ImageButton3, lv_color_hex(0xB10C0C), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_img_recolor_opa(ui_ImageButton3, 150, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Panel4 = lv_obj_create(ui_ImageButton3);
    lv_obj_set_width(ui_Panel4, 40);
    lv_obj_set_height(ui_Panel4, 41);
    lv_obj_set_x(ui_Panel4, 2);
    lv_obj_set_y(ui_Panel4, -1);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ButtonParam, ui_event_ButtonParam, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SwitchAuto, ui_event_SwitchAuto, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonPower, ui_event_ButtonPower, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonJointArm1, ui_event_ButtonJointArm1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonJointArm2, ui_event_ButtonJointArm2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonJointArm3, ui_event_ButtonJointArm3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PanelRight, ui_event_PanelRight, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PanelUp, ui_event_PanelUp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PanelDown, ui_event_PanelDown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PanelMid, ui_event_PanelMid, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PanelLeft, ui_event_PanelLeft, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel1, ui_event_Panel1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel2, ui_event_Panel2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel3, ui_event_Panel3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel4, ui_event_Panel4, LV_EVENT_ALL, NULL);

}
