// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: ESP32Box

#include "../ui.h"

void ui_ScreenACT_screen_init(void)
{
    ui_ScreenACT = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenACT, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenACT, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenACT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonParam6 = lv_btn_create(ui_ScreenACT);
    lv_obj_set_width(ui_ButtonParam6, 70);
    lv_obj_set_height(ui_ButtonParam6, 28);
    lv_obj_set_x(ui_ButtonParam6, 117);
    lv_obj_set_y(ui_ButtonParam6, -103);
    lv_obj_set_align(ui_ButtonParam6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonParam6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonParam6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonParam6, lv_color_hex(0xF3E4E4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonParam6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label30 = lv_label_create(ui_ButtonParam6);
    lv_obj_set_width(ui_Label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label30, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label30, "Back");
    lv_obj_clear_flag(ui_Label30, LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_obj_set_style_text_color(ui_Label30, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label30, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelLocal8 = lv_label_create(ui_ScreenACT);
    lv_obj_set_width(ui_LabelLocal8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelLocal8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelLocal8, -102);
    lv_obj_set_y(ui_LabelLocal8, -104);
    lv_obj_set_align(ui_LabelLocal8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelLocal8, "ACT:");

    ui_LabelIP1 = lv_label_create(ui_ScreenACT);
    lv_obj_set_width(ui_LabelIP1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelIP1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelIP1, -6);
    lv_obj_set_y(ui_LabelIP1, -104);
    lv_obj_set_align(ui_LabelIP1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelIP1, "Model Disconnect");

    ui_ButtonLight5 = lv_btn_create(ui_ScreenACT);
    lv_obj_set_width(ui_ButtonLight5, 23);
    lv_obj_set_height(ui_ButtonLight5, 18);
    lv_obj_set_x(ui_ButtonLight5, -139);
    lv_obj_set_y(ui_ButtonLight5, -105);
    lv_obj_set_align(ui_ButtonLight5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonLight5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonLight5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonLight5, 55, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_ButtonLight5, lv_color_hex(0xCCCCEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_ButtonLight5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ButtonLight5, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BarACTrate = lv_bar_create(ui_ScreenACT);
    lv_bar_set_mode(ui_BarACTrate, LV_BAR_MODE_RANGE);
    lv_bar_set_value(ui_BarACTrate, 15, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_BarACTrate, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_BarACTrate, 275);
    lv_obj_set_height(ui_BarACTrate, 10);
    lv_obj_set_x(ui_BarACTrate, 0);
    lv_obj_set_y(ui_BarACTrate, 104);
    lv_obj_set_align(ui_BarACTrate, LV_ALIGN_CENTER);

    ui_LabelACTrate = lv_label_create(ui_ScreenACT);
    lv_obj_set_width(ui_LabelACTrate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelACTrate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelACTrate, -3);
    lv_obj_set_y(ui_LabelACTrate, 103);
    lv_obj_set_align(ui_LabelACTrate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelACTrate, "0.0%");

    ui_ButtonParam7 = lv_btn_create(ui_ScreenACT);
    lv_obj_set_width(ui_ButtonParam7, 130);
    lv_obj_set_height(ui_ButtonParam7, 40);
    lv_obj_set_x(ui_ButtonParam7, 6);
    lv_obj_set_y(ui_ButtonParam7, -38);
    lv_obj_set_align(ui_ButtonParam7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonParam7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonParam7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonParam7, lv_color_hex(0xF3E4E4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonParam7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label31 = lv_label_create(ui_ButtonParam7);
    lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label31, -1);
    lv_obj_set_y(ui_Label31, 0);
    lv_obj_set_align(ui_Label31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label31, "Record Action");
    lv_obj_clear_flag(ui_Label31, LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_obj_set_style_text_color(ui_Label31, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label31, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonParam9 = lv_btn_create(ui_ScreenACT);
    lv_obj_set_width(ui_ButtonParam9, 130);
    lv_obj_set_height(ui_ButtonParam9, 40);
    lv_obj_set_x(ui_ButtonParam9, 6);
    lv_obj_set_y(ui_ButtonParam9, 12);
    lv_obj_set_align(ui_ButtonParam9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonParam9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonParam9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonParam9, lv_color_hex(0xF3E4E4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonParam9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label33 = lv_label_create(ui_ButtonParam9);
    lv_obj_set_width(ui_Label33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label33, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label33, "Replay Action");
    lv_obj_clear_flag(ui_Label33, LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_obj_set_style_text_color(ui_Label33, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label33, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonParam10 = lv_btn_create(ui_ScreenACT);
    lv_obj_set_width(ui_ButtonParam10, 130);
    lv_obj_set_height(ui_ButtonParam10, 40);
    lv_obj_set_x(ui_ButtonParam10, 6);
    lv_obj_set_y(ui_ButtonParam10, 60);
    lv_obj_set_align(ui_ButtonParam10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonParam10, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonParam10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonParam10, lv_color_hex(0xF3E4E4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonParam10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label34 = lv_label_create(ui_ButtonParam10);
    lv_obj_set_width(ui_Label34, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label34, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label34, -1);
    lv_obj_set_y(ui_Label34, 0);
    lv_obj_set_align(ui_Label34, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label34, "Perception");
    lv_obj_clear_flag(ui_Label34, LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_obj_set_style_text_color(ui_Label34, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label34, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DropdownReplay = lv_dropdown_create(ui_ScreenACT);
    lv_dropdown_set_options(ui_DropdownReplay, "A0\nA1\nA2\nA3\nA4\nA5\nA6\nA7\nA8\nA9");
    lv_obj_set_width(ui_DropdownReplay, 78);
    lv_obj_set_height(ui_DropdownReplay, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DropdownReplay, -111);
    lv_obj_set_y(ui_DropdownReplay, 12);
    lv_obj_set_align(ui_DropdownReplay, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DropdownReplay, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_DropdownModel = lv_dropdown_create(ui_ScreenACT);
    lv_dropdown_set_options(ui_DropdownModel, "M0\nM1\nM2\nM3\nM4\nM5\nM6\nM7\nM8\nM9");
    lv_obj_set_width(ui_DropdownModel, 78);
    lv_obj_set_height(ui_DropdownModel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DropdownModel, -111);
    lv_obj_set_y(ui_DropdownModel, 61);
    lv_obj_set_align(ui_DropdownModel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DropdownModel, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_DropdownRecord = lv_dropdown_create(ui_ScreenACT);
    lv_dropdown_set_options(ui_DropdownRecord, "R0\nR1\nR2\nR4\nR5\nR6\nR7\nR8\nR9");
    lv_obj_set_width(ui_DropdownRecord, 78);
    lv_obj_set_height(ui_DropdownRecord, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DropdownRecord, -111);
    lv_obj_set_y(ui_DropdownRecord, -37);
    lv_obj_set_align(ui_DropdownRecord, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DropdownRecord, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_ButtonParam11 = lv_btn_create(ui_ScreenACT);
    lv_obj_set_width(ui_ButtonParam11, 58);
    lv_obj_set_height(ui_ButtonParam11, 138);
    lv_obj_set_x(ui_ButtonParam11, 118);
    lv_obj_set_y(ui_ButtonParam11, 12);
    lv_obj_set_align(ui_ButtonParam11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonParam11, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonParam11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonParam11, lv_color_hex(0xA20000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonParam11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label35 = lv_label_create(ui_ButtonParam11);
    lv_obj_set_width(ui_Label35, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label35, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label35, -1);
    lv_obj_set_y(ui_Label35, 0);
    lv_obj_set_align(ui_Label35, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label35, "Stop");
    lv_obj_clear_flag(ui_Label35, LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_obj_set_style_text_color(ui_Label35, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label35, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabViewACT = lv_tabview_create(ui_ScreenACT, LV_DIR_TOP, 25);
    lv_obj_set_width(ui_TabViewACT, 218);
    lv_obj_set_height(ui_TabViewACT, 27);
    lv_obj_set_x(ui_TabViewACT, -39);
    lv_obj_set_y(ui_TabViewACT, -76);
    lv_obj_set_align(ui_TabViewACT, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TabViewACT, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_TabViewACT, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TabViewACT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TabViewACT, 1, LV_PART_MAIN | LV_STATE_DEFAULT);


    lv_obj_add_event_cb(ui_ButtonParam6, ui_event_ButtonParam6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BarACTrate, ui_event_BarACTrate, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonParam7, ui_event_ButtonParam7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonParam9, ui_event_ButtonParam9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonParam10, ui_event_ButtonParam10, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonParam11, ui_event_ButtonParam11, LV_EVENT_ALL, NULL);

}
