// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: ESP32Box

#include "../ui.h"

void ui_Start_screen_init(void)
{
    ui_Start = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Start, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Start, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Start, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_Start);
    lv_img_set_src(ui_Image1, &ui_img_1822533526);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 351
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 233
    lv_obj_set_x(ui_Image1, -13);
    lv_obj_set_y(ui_Image1, -10);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image1, 200);

    ui_Spinner1 = lv_spinner_create(ui_Start, 1000, 90);
    lv_obj_set_width(ui_Spinner1, 107);
    lv_obj_set_height(ui_Spinner1, 97);
    lv_obj_set_x(ui_Spinner1, 94);
    lv_obj_set_y(ui_Spinner1, -32);
    lv_obj_set_align(ui_Spinner1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_img_src(ui_Spinner1, &ui_img_1822533526, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Spinner1, lv_color_hex(0x4040FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Spinner1, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Spinner1, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Label21 = lv_label_create(ui_Start);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label21, -2);
    lv_obj_set_y(ui_Label21, 102);
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "OmniRobTele: Operate Any Robots...");

    lv_obj_add_event_cb(ui_Label21, ui_event_Label21, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Start, ui_event_Start, LV_EVENT_ALL, NULL);

}
